### ISSUE TITLE
Installation on Debian Jessie fails

### ISSUE THREAD

**Issue by analbeard** [ceph/ceph-ansible#1003]
Attempting to deploy a cluster on Debian Jessie fails, and with my limited experience with Ansible it appears to be due to the syntax being out of date.

``` yaml
TASK [ceph.ceph-common : install dependencies] *********************************
failed: [172.16.0.51] (item=[u'debian_package_dependencies']) => {"failed": true, "item": ["debian_package_dependencies"], "msg": "No package matching 'debian_package_dependencies' is available"}
failed: [172.16.0.53] (item=[u'debian_package_dependencies']) => {"failed": true, "item": ["debian_package_dependencies"], "msg": "No package matching 'debian_package_dependencies' is available"}
failed: [172.16.0.52] (item=[u'debian_package_dependencies']) => {"failed": true, "item": ["debian_package_dependencies"], "msg": "No package matching 'debian_package_dependencies' is available"}
```

I then changed `roles/ceph.ceph-common/tasks/installs/install_on_debian.yml` from:

``` yaml
- name: install dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: debian_package_dependencies
```

to:

``` yaml
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{debian_package_dependencies}}"
```

This change was sufficient to get past the package installation tasks (obviously the same needed to be applied to the `install ceph` task in the same file). I then hit the following:

``` yaml
TASK [ceph.ceph-common : generate ceph configuration file] *********************
fatal: [172.16.0.51]: FAILED! => {"failed": true, "msg": "module (config_template) is missing interpreter line"}
fatal: [172.16.0.52]: FAILED! => {"failed": true, "msg": "module (config_template) is missing interpreter line"}
fatal: [172.16.0.53]: FAILED! => {"failed": true, "msg": "module (config_template) is missing interpreter line"}
```

At this point I'm not sure where to go to resolve this - trying to pick my way through everything is a bit optimistic given that I've hardly used Ansible ;)

I'm building a cluster with Terraform on Openstack for testing purposes so it's easy enough to kill everything off and start again to test changes if you need me to.

**Comment by leseb** [comment]
Thanks for reporting the issue, your fix is valid for Ansible v2.
For the configuration file generation, did you follow https://github.com/ceph/ceph-ansible/tree/master/roles/ceph-common#requirements ?

**Comment by analbeard** [comment]
Ah no, somehow I missed that entirely - I'll do that and report back. 

I fixed the issues I've found so far in my own fork (one related to the Ansible install script too) - I can create a pull request if you'd like? https://github.com/ceph/ceph-ansible/compare/master...analbeard:master

**Comment by leseb** [comment]
Yes please create a PR :)

**Comment by analbeard** [comment]
So the next issue I appear to hit seems to be related to deprecated Ansible functions when generating ceph.conf.

```yaml
TASK [ceph.ceph-common : generate ceph configuration file] *********************
task path: /tmp/ansible/roles/ceph.ceph-common/tasks/main.yml:230
<172.16.0.51> ESTABLISH SSH CONNECTION FOR USER: None
<172.16.0.51> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 172.16.0.51 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1476038874.22-80337242418091 `" && echo ansible-tmp-1476038874.22-80337242418091="` echo $HOME/.ansible/tmp/ansible-tmp-1476038874.22-80337242418091 `" ) && sleep 0'"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.3.0-py2.7.egg/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.3.0-py2.7.egg/ansible/executor/task_executor.py", line 488, in _execute
    result = self._handler.run(task_vars=variables)
  File "/tmp/ansible/plugins/actions/_v2_config_template.py", line 481, in run
    _status, _vars = self._load_options_and_status(task_vars=task_vars)
  File "/tmp/ansible/plugins/actions/_v2_config_template.py", line 419, in _load_options_and_status
    faf = self._task.first_available_file
AttributeError: 'Task' object has no attribute 'first_available_file'

fatal: [172.16.0.51]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
````

As you can see, my Ansible working dir is /tmp/ansible, I've copied config_template.py to /tmp/ansible and my ansible.cfg is the default:

```
[defaults]
ansible_managed = Please do not change this file directly since it is managed by Ansible and will be overwritten
action_plugins = plugins/actions
```

As far as I can tell I haven't missed anything, but please do correct me if I'm wrong!

**Comment by leseb** [comment]
@cloudnull hum any idea?
It works for me on v2 without any issue...

**Comment by analbeard** [comment]
Just in case it helps, my ansible info:

```
root@tf-ceph-adm-1:/tmp/ansible# ansible --version
ansible 2.3.0
  config file = /tmp/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

And I'm running as the user 'ceph' which I create when I provision the cluster.

**Comment by cloudnull** [comment]
I'll have to look into the module for support with ansible 2.3 (currently unreleased); I've not taken a look at it quite yet. For the time being I'd recommend sticking with 2.{1,2} as devel is likely to be full of pain other unexpected pain.

**Comment by analbeard** [comment]
@cloudnull thanks for that - I didn't realise that the install-ansible.sh automatically build the devel branch (head points to devel so it's the standard behaviour). I've amended my install script to use stable-2.2 for the moment, and I'm still seeing the issue as described above.

**Comment by analbeard** [comment]
Sadly I'm still no further along with this, I've tried to take a look at the config template but to be perfectly honest I'm not entirely sure how that particular file functions so I can't even begin to modify it.

**Comment by leseb** [comment]
No activity. Closing this, feel free to re-open.
