### ISSUE TITLE
Ansible/Docker for CentOS 7 (using vagrant virtualbox) fails during OSD disk prepare

### ISSUE THREAD

**Issue by dhirajh** [ceph/ceph-ansible#1046]
I have successfully used an older version of ansible/docker on vagrant playbook to setup a Ceph cluster using the image bento/centos-7.2. I recently did an update and noticed that "SATA Controller" in no longer specified while creating disks via vagrant on virtual box. I am running into errors when I try to deploy using this new setup. It happens during the OSD PREPARE phase and does not happen to all OSDs, just some. Here is error:

```
[vagrant@ceph-osd2 ~]$ sudo docker logs b6b08a33ba7d
static: does not generate config
HEALTH_ERR 64 pgs are stuck inactive for more than 300 seconds; 64 pgs stuck inactive; no osds
Error: /dev/sdc: unrecognised disk label
Error: /dev/sdc: unrecognised disk label
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
set_type: Will colocate journal with data on /dev/sdc
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
ptype_tobe_for_name: name = journal
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
create_partition: Creating journal partition num 2 size 100 on /dev/sdc
command_check_call: Running command: /usr/sbin/sgdisk --new=2:0:+100M --change-name=2:ceph journal --partition-guid=2:cb376528-281d-4b86-ae54-890bcfe5c372 --typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106 --mbrtogpt -- /dev/sdc
Creating new GPT entries.
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdc /usr/sbin/partprobe /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc2 uuid path is /sys/dev/block/8:34/dm/uuid
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/cb376528-281d-4b86-ae54-890bcfe5c372
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/cb376528-281d-4b86-ae54-890bcfe5c372
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
set_data_partition: Creating osd partition on /dev/sdc
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
ptype_tobe_for_name: name = data
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
create_partition: Creating data partition num 1 size 0 on /dev/sdc
command_check_call: Running command: /usr/sbin/sgdisk --largest-new=1 --change-name=1:ceph data --partition-guid=1:23e2e067-5b3a-43e4-a2af-f6d9175b36b4 --typecode=1:89c57f98-2fe5-4dc0-89c1-f3ad0ceff2be --mbrtogpt -- /dev/sdc
update_partition: Calling partprobe on created device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdc /usr/sbin/partprobe /dev/sdc
The operation has completed successfully.
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc1 uuid path is /sys/dev/block/8:33/dm/uuid
populate_data_path_device: Creating xfs fs on /dev/sdc1
command_check_call: Running command: /usr/sbin/mkfs -t xfs -f -i size=2048 -f -- /dev/sdc1
/dev/sdc1: No such file or directory
Usage: mkfs.xfs
/\* blocksize _/     [-b log=n|size=num]
/_ metadata _/      [-m crc=0|1,finobt=0|1]
/_ data subvol _/   [-d agcount=n,agsize=n,file,name=xxx,size=num,
                (sunit=value,swidth=value|su=num,sw=num|noalign),
                sectlog=n|sectsize=num
/_ force overwrite _/   [-f]
/_ inode size _/    [-i log=n|perblock=n|size=num,maxpct=n,attr=0|1|2,
                projid32bit=0|1]
/_ no discard _/    [-K]
/_ log subvol _/    [-l agnum=n,internal,size=num,logdev=xxx,version=n
                sunit=value|su=num,sectlog=n|sectsize=num,
                lazy-count=0|1]
/_ label _/     [-L label (maximum 12 characters)]
/_ naming _/        [-n log=n|size=num,version=2|ci,ftype=0|1]
/_ no-op info only _/   [-N]
/_ prototype file _/    [-p fname]
/_ quiet _/     [-q]
/_ realtime subvol _/   [-r extsize=num,size=num,rtdev=xxx]
/_ sectorsize _/    [-s log=n|size=num]
/_ version _/       [-V]
            devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5011, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 4962, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1791, in main
    Prepare.factory(args).prepare()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1779, in prepare
    self.prepare_locked()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1811, in prepare_locked
    self.data.prepare(self.journal)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2463, in prepare
    self.prepare_device(_to_prepare_list)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2641, in prepare_device
    self.populate_data_path_device(*to_prepare_list)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2596, in populate_data_path_device
    raise Error(e)
ceph_disk.main.Error: Error: Command '['/usr/sbin/mkfs', '-t', 'xfs', '-f', '-i', 'size=2048', '-f', '--', '/dev/sdc1']' returned non-zero exit status 1
```
# 

The interesting thing to note here is that if I ssh to the OSD and manually retry the prepare, it succeeds with the following output:
# 

```
sudo docker run --net=host --pid=host --privileged=true --name=ceph-osd2-osd-prepare-devsdc2 -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -e OSD_DEVICE=/dev/sdc -e OSD_FORCE_ZAP=1 -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE ceph/daemon:tag-build-master-jewel-centos-7
static: does not generate config
HEALTH_ERR 64 pgs are stuck inactive for more than 300 seconds; 64 pgs degraded; 64 pgs stuck inactive; 64 pgs undersized
It looks like /dev/sdc is an OSD, however OSD_FORCE_ZAP is enabled so we are zapping the device anyway
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
zap: Zapping partition table on /dev/sdc
command_check_call: Running command: /usr/sbin/sgdisk --zap-all -- /dev/sdc
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.

Warning! One or more CRCs don't match. You should repair the disk!
---

Caution: Found protective or hybrid MBR and corrupt GPT. Using GPT, but disk
verification and recovery are STRONGLY recommended.
---

GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
command_check_call: Running command: /usr/sbin/sgdisk --clear --mbrtogpt -- /dev/sdc
Creating new GPT entries.
The operation has completed successfully.
update_partition: Calling partprobe on zapped device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdc /usr/sbin/partprobe /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
set_type: Will colocate journal with data on /dev/sdc
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
ptype_tobe_for_name: name = journal
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
create_partition: Creating journal partition num 2 size 100 on /dev/sdc
command_check_call: Running command: /usr/sbin/sgdisk --new=2:0:+100M --change-name=2:ceph journal --partition-guid=2:4cce7dbc-0cd8-4f30-8221-72b73957c9cd --typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106 --mbrtogpt -- /dev/sdc
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdc /usr/sbin/partprobe /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc2 uuid path is /sys/dev/block/8:34/dm/uuid
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/4cce7dbc-0cd8-4f30-8221-72b73957c9cd
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/4cce7dbc-0cd8-4f30-8221-72b73957c9cd
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
set_data_partition: Creating osd partition on /dev/sdc
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
ptype_tobe_for_name: name = data
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
create_partition: Creating data partition num 1 size 0 on /dev/sdc
command_check_call: Running command: /usr/sbin/sgdisk --largest-new=1 --change-name=1:ceph data --partition-guid=1:5c330275-7d35-4d2e-a470-dba2a8fcd848 --typecode=1:89c57f98-2fe5-4dc0-89c1-f3ad0ceff2be --mbrtogpt -- /dev/sdc
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdc /usr/sbin/partprobe /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc1 uuid path is /sys/dev/block/8:33/dm/uuid
populate_data_path_device: Creating xfs fs on /dev/sdc1
command_check_call: Running command: /usr/sbin/mkfs -t xfs -f -i size=2048 -f -- /dev/sdc1
meta-data=/dev/sdc1              isize=2048   agcount=4, agsize=697535 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=0        finobt=0
data     =                       bsize=4096   blocks=2790139, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=0
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
mount: Mounting /dev/sdc1 on /var/lib/ceph/tmp/mnt.NTJwKe with options noatime,largeio,inode64,swalloc
command_check_call: Running command: /usr/bin/mount -t xfs -o noatime,largeio,inode64,swalloc -- /dev/sdc1 /var/lib/ceph/tmp/mnt.NTJwKe
command: Running command: /usr/sbin/restorecon /var/lib/ceph/tmp/mnt.NTJwKe
populate_data_path: Preparing osd data dir /var/lib/ceph/tmp/mnt.NTJwKe
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.NTJwKe/ceph_fsid.14596.tmp
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.NTJwKe/ceph_fsid.14596.tmp
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.NTJwKe/fsid.14596.tmp
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.NTJwKe/fsid.14596.tmp
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.NTJwKe/magic.14596.tmp
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.NTJwKe/magic.14596.tmp
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.NTJwKe/journal_uuid.14596.tmp
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.NTJwKe/journal_uuid.14596.tmp
adjust_symlink: Creating symlink /var/lib/ceph/tmp/mnt.NTJwKe/journal -> /dev/disk/by-partuuid/4cce7dbc-0cd8-4f30-8221-72b73957c9cd
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.NTJwKe
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.NTJwKe
unmount: Unmounting /var/lib/ceph/tmp/mnt.NTJwKe
command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.NTJwKe
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
command_check_call: Running command: /usr/sbin/sgdisk --typecode=1:4fbd7e29-9d25-41b8-afd0-062c0ceff05d -- /dev/sdc
The operation has completed successfully.
update_partition: Calling partprobe on prepared device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdc /usr/sbin/partprobe /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command_check_call: Running command: /usr/bin/udevadm trigger --action=add --sysname-match sdc1
```

**Comment by leseb** [comment]
This is normal if the second attempt works because you used `FORCE_ZAP`, as a result this will destroy all partitions data.
The initial error is here:

```
Error: /dev/sdc: unrecognised disk label
Error: /dev/sdc: unrecognised disk label
```

Would you mind ssh'ing again after the provisioning sequence only?
So only run `vagrant up --no-provision`, then ssh into an OSD and run 

* `lsblk`
* `parted /dev/sdb print`

Thanks!

**Comment by dhirajh** [comment]
@leseb
I had a question about the second attempt you had suggested. Is the ansible playbook supposed to be idempotent? it currently checks for presence of some conf files and keyrings. If it finds them, then it throws an error about exisiting configs, so it isn't really idempotent.

On the information you had asked, here is the output:

NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT

sda               8:0    0   40G  0 disk 

├─sda1            8:1    0  500M  0 part /boot

└─sda2            8:2    0 39.5G  0 part 

  ├─centos-root 253:0    0 38.5G  0 lvm  /

  └─centos-swap 253:1    0    1G  0 lvm  [SWAP]

sdb               8:16   0 10.8G  0 disk 

sdc               8:32   0 10.8G  0 disk 


[vagrant@ceph-osd0 ~]$ sudo parted /dev/sdb print
Error: /dev/sdb: unrecognised disk label
Model: ATA VBOX HARDDISK (scsi)                                           
Disk /dev/sdb: 11.5GB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags:

**Comment by leseb** [comment]
@dhirajh well yes it's idempotent, if nothing is up and there are files, then this means a previous attempts to run a cluster failed and we can not take the risk to boostrap.

**Comment by dhirajh** [comment]
@leseb that is true. Quite often, while bringing up a new cluster, the files are copied just fine, but the OSd fails to come up. So one has to manually wipe these files. I guess I could create a task which wipes out these files if one doesn't already exist.

**Comment by leseb** [comment]
@dhirajh wiping files might be handy while doing testing but can be catastrophic if a real cluster used to present...
