### ISSUE TITLE
ceph-disk services failed after reboot

### ISSUE THREAD

**Issue by D3N14L** [ceph/ceph-ansible#1444]
Hi all,

we are using ceph ansible v2.1.0 and our systemd reports failed services (for all ceph-disk@dev-sd*.service)  after a reboot of a osd node:
```
Apr 13 07:11:27 blk0002 systemd[1]: Starting Ceph disk activation: /dev/sdv1...
Apr 13 07:11:27 blk0002 sh[5540]: main_trigger: main_trigger: Namespace(cluster='ceph', dev='/dev/sdv1', dmcrypt=None, dmcrypt_key_dir=
Apr 13 07:11:27 blk0002 sh[5540]: command: Running command: /sbin/init --version
Apr 13 07:11:27 blk0002 sh[5540]: command_check_call: Running command: /bin/chown ceph:ceph /dev/sdv1
Apr 13 07:11:27 blk0002 sh[5540]: command: Running command: /sbin/blkid -o udev -p /dev/sdv1
Apr 13 07:11:27 blk0002 sh[5540]: command: Running command: /sbin/blkid -o udev -p /dev/sdv1
Apr 13 07:11:27 blk0002 sh[5540]: main_trigger: trigger /dev/sdv1 parttype 4fbd7e29-9d25-41b8-afd0-062c0ceff05d uuid c37de139-206f-48db
Apr 13 07:11:27 blk0002 sh[5540]: command: Running command: /usr/sbin/ceph-disk --verbose activate /dev/sdv1
Apr 13 07:13:27 blk0002 systemd[1]: ceph-disk@dev-sdv1.service: Main process exited, code=exited, status=124/n/a
Apr 13 07:13:27 blk0002 systemd[1]: Failed to start Ceph disk activation: /dev/sdv1.
Apr 13 07:13:27 blk0002 systemd[1]: ceph-disk@dev-sdv1.service: Unit entered failed state.
Apr 13 07:13:27 blk0002 systemd[1]: ceph-disk@dev-sdv1.service: Failed with result 'exit-code'.
```
The strange thing is that the osds seem to start normally and enter the cluster as expected.

Doing a `systemctl start ceph-disk@dev-sdv1.service` the service starts normally:
```
Apr 13 07:36:03 blk0002 systemd[1]: Starting Ceph disk activation: /dev/sdv1...
Apr 13 07:36:03 blk0002 sh[16293]: main_trigger: main_trigger: Namespace(cluster='ceph', dev='/dev/sdv1', dmcrypt=None, dmcrypt_key_dir
Apr 13 07:36:03 blk0002 sh[16293]: command: Running command: /sbin/init --version
Apr 13 07:36:03 blk0002 sh[16293]: command_check_call: Running command: /bin/chown ceph:ceph /dev/sdv1
Apr 13 07:36:03 blk0002 sh[16293]: command: Running command: /sbin/blkid -o udev -p /dev/sdv1
Apr 13 07:36:03 blk0002 sh[16293]: command: Running command: /sbin/blkid -o udev -p /dev/sdv1
Apr 13 07:36:03 blk0002 sh[16293]: main_trigger: trigger /dev/sdv1 parttype 4fbd7e29-9d25-41b8-afd0-062c0ceff05d uuid c37de139-206f-48d
Apr 13 07:36:03 blk0002 sh[16293]: command: Running command: /usr/sbin/ceph-disk --verbose activate /dev/sdv1
Apr 13 07:36:04 blk0002 sh[16293]: main_trigger:
Apr 13 07:36:04 blk0002 sh[16293]: main_trigger: main_activate: path = /dev/sdv1
Apr 13 07:36:04 blk0002 sh[16293]: get_dm_uuid: get_dm_uuid /dev/sdv1 uuid path is /sys/dev/block/65:81/dm/uuid
Apr 13 07:36:04 blk0002 sh[16293]: command: Running command: /sbin/blkid -o udev -p /dev/sdv1
Apr 13 07:36:04 blk0002 sh[16293]: command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sdv1
Apr 13 07:36:04 blk0002 sh[16293]: command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_x
Apr 13 07:36:04 blk0002 sh[16293]: mount: Mounting /dev/sdv1 on /var/lib/ceph/tmp/mnt.GmGGJG with options noatime,largeio,inode64,swall
Apr 13 07:36:04 blk0002 sh[16293]: command_check_call: Running command: /bin/mount -t xfs -o noatime,largeio,inode64,swalloc -- /dev/sd
Apr 13 07:36:04 blk0002 sh[16293]: activate: Cluster uuid is 9621dc64-2b99-49d9-8746-668a7d5c3597
Apr 13 07:36:04 blk0002 sh[16293]: command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
Apr 13 07:36:04 blk0002 sh[16293]: activate: Cluster name is ceph
Apr 13 07:36:04 blk0002 sh[16293]: activate: OSD uuid is c37de139-206f-48db-96c9-abea66416673
Apr 13 07:36:04 blk0002 sh[16293]: activate: OSD id is 32
Apr 13 07:36:04 blk0002 sh[16293]: command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup init
Apr 13 07:36:04 blk0002 sh[16293]: command: Running command: /usr/bin/ceph-detect-init --default sysvinit
Apr 13 07:36:04 blk0002 sh[16293]: activate: Marking with init system systemd
Apr 13 07:36:04 blk0002 sh[16293]: command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.GmGGJG/systemd
Apr 13 07:36:04 blk0002 sh[16293]: activate: ceph osd.32 data dir is ready at /var/lib/ceph/tmp/mnt.GmGGJG
Apr 13 07:36:04 blk0002 sh[16293]: mount_activate: ceph osd.32 already mounted in position; unmounting ours.
Apr 13 07:36:04 blk0002 sh[16293]: unmount: Unmounting /var/lib/ceph/tmp/mnt.GmGGJG
Apr 13 07:36:04 blk0002 sh[16293]: command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.GmGGJG
Apr 13 07:36:04 blk0002 sh[16293]: start_daemon: Starting ceph osd.32...
Apr 13 07:36:04 blk0002 sh[16293]: command_check_call: Running command: /bin/systemctl disable ceph-osd@32
Apr 13 07:36:04 blk0002 sh[16293]: command_check_call: Running command: /bin/systemctl enable --runtime ceph-osd@32
daniel.marks@blk0002.dev10:/var/log > sudo less /usr/sbin/ceph-disk
```
Is anyone else seeing this?

**Comment by yrjo** [comment]
Hi,
are you using LVM, especially for /var or /var/lib?

I had similar problem - even running 
`ceph-disk activate all`
was able to activate all disks on OSD node.

In which state do you have OSDs after boot, running 
`ceph-disk list`
on OSD node?

I have spent tons of time on that as after fresh deployment that was the biggest problem I faced there..
Then I have realized that after having /var out of LVM, as normal partition it is automagically  okey..

It is not ideal way, as rest of FSs are on LVM, 
but even playing with systemd, postponing OSD services/targets, playing with LVM didnt help me so far...and /var out of LVM is somehow working.. 
just try it.. maybe you will have the same issue as I had

cheers

**Comment by D3N14L** [comment]
Hi yrjo

I am not using LVM on the nodes at all.

```
# ceph-disk list
/dev/loop0 other, unknown
/dev/loop1 other, unknown
/dev/loop2 other, unknown
/dev/loop3 other, unknown
/dev/loop4 other, unknown
/dev/loop5 other, unknown
/dev/loop6 other, unknown
/dev/loop7 other, unknown
/dev/sda :
 /dev/sda1 other, ext4, mounted on /
/dev/sdb :
 /dev/sdb1 ceph data, active, cluster ceph, osd.36, journal /dev/sdj1
/dev/sdc :
 /dev/sdc1 ceph data, active, cluster ceph, osd.40, journal /dev/sdk1
/dev/sdd :
 /dev/sdd1 ceph data, active, cluster ceph, osd.43, journal /dev/sdj2
/dev/sde :
 /dev/sde1 ceph data, active, cluster ceph, osd.46, journal /dev/sdk2
/dev/sdf :
 /dev/sdf1 ceph data, active, cluster ceph, osd.49, journal /dev/sdj3
/dev/sdg :
 /dev/sdg1 ceph data, active, cluster ceph, osd.51, journal /dev/sdk3
/dev/sdh :
 /dev/sdh1 ceph data, active, cluster ceph, osd.54, journal /dev/sdj4
/dev/sdi :
 /dev/sdi1 ceph data, active, cluster ceph, osd.58, journal /dev/sdk4
/dev/sdj :
 /dev/sdj1 ceph journal, for /dev/sdb1
 /dev/sdj2 ceph journal, for /dev/sdd1
 /dev/sdj3 ceph journal, for /dev/sdf1
 /dev/sdj4 ceph journal, for /dev/sdh1
/dev/sdk :
 /dev/sdk1 ceph journal, for /dev/sdc1
 /dev/sdk2 ceph journal, for /dev/sde1
 /dev/sdk3 ceph journal, for /dev/sdg1
 /dev/sdk4 ceph journal, for /dev/sdi1
/dev/sdl :
 /dev/sdl2 ceph journal, for /dev/sdl1
 /dev/sdl1 ceph data, active, cluster ceph, osd.1, journal /dev/sdl2
/dev/sdm :
 /dev/sdm2 ceph journal, for /dev/sdm1
 /dev/sdm1 ceph data, active, cluster ceph, osd.4, journal /dev/sdm2
/dev/sdn :
 /dev/sdn2 ceph journal, for /dev/sdn1
 /dev/sdn1 ceph data, active, cluster ceph, osd.7, journal /dev/sdn2
/dev/sdo :
 /dev/sdo2 ceph journal, for /dev/sdo1
 /dev/sdo1 ceph data, active, cluster ceph, osd.10, journal /dev/sdo2
/dev/sdp :
 /dev/sdp2 ceph journal, for /dev/sdp1
 /dev/sdp1 ceph data, active, cluster ceph, osd.13, journal /dev/sdp2
/dev/sdq :
 /dev/sdq2 ceph journal, for /dev/sdq1
 /dev/sdq1 ceph data, active, cluster ceph, osd.16, journal /dev/sdq2
/dev/sdr :
 /dev/sdr2 ceph journal, for /dev/sdr1
 /dev/sdr1 ceph data, active, cluster ceph, osd.19, journal /dev/sdr2
/dev/sds :
 /dev/sds2 ceph journal, for /dev/sds1
 /dev/sds1 ceph data, active, cluster ceph, osd.22, journal /dev/sds2
/dev/sdt :
 /dev/sdt2 ceph journal, for /dev/sdt1
 /dev/sdt1 ceph data, active, cluster ceph, osd.25, journal /dev/sdt2
/dev/sdu :
 /dev/sdu2 ceph journal, for /dev/sdu1
 /dev/sdu1 ceph data, active, cluster ceph, osd.28, journal /dev/sdu2
/dev/sdv :
 /dev/sdv2 ceph journal, for /dev/sdv1
 /dev/sdv1 ceph data, active, cluster ceph, osd.32, journal /dev/sdv2
/dev/sdw :
 /dev/sdw2 ceph journal, for /dev/sdw1
 /dev/sdw1 ceph data, active, cluster ceph, osd.35, journal /dev/sdw2
```

**Comment by c744402859** [comment]
vim  /var/log/messages 
key words ：
   May 26 08:06:44 node01 systemd: Starting Ceph disk activation: /dev/sdb3...
and
   May 26 08:08:44 node01 systemd: Failed to start Ceph disk activation: /dev/sdb3.

From the start up to the startup failure cost 120s,  ceph-disk@service timeout!! 
vim /usr/lib/systemd/system/ceph-disk@.service
  1 [Unit]
  2 Description=Ceph disk activation: %f
  3
  4 [Service]
  5 Type=oneshot
  6 KillMode=none
  7 ExecStart=/bin/sh -c 'timeout 120 flock /var/lock/ceph-disk /usr/sbin/ceph-disk --verbose --log-stdout trigger --sync %f'
  8 TimeoutSec=0

Hope this helps!  :)

**Comment by leseb** [comment]
Which version of Ceph are you deploying? Because on Kraken, I don't see any ceph-disk unit file.

**Comment by D3N14L** [comment]
We are using Jewel.

**Comment by leseb** [comment]
No activity. Closing this, feel free to re-open.

**Comment by mehdy** [comment]
I'm having the exact same issue. I was wondering if there are any solutions?
@D3N14L

**Comment by D3N14L** [comment]
@mehdy : As we only saw failed systemd services, but the actual ceph-osd processes were running properly, we did not see this as a real issue. As leseb said: there are no ceph-disk unit files on kraken, so the solution for us would be to update to kraken, to get rid of the defective service files. 

So - no. No solution for jewel.

**Comment by discostur** [comment]
I just deployed a cluster with the latest master version from ceph-ansible playbook and ceph version 12.2.0. I think i ran into the same problem:

```
/var/log/ceph/ceph-osd.0.log

2017-08-30 16:25:20.093394 7f0acb0d4d00  0 set uid:gid to 167:167 (ceph:ceph)
2017-08-30 16:25:20.093422 7f0acb0d4d00  0 ceph version 12.2.0 (32ce2a3ae5239ee33d6150705cdb24d43bab910c) luminous (rc), process (unknown), pid 6669
2017-08-30 16:25:20.093712 7f0acb0d4d00 -1 ^[[0;31m ** ERROR: unable to open OSD superblock on /var/lib/ceph/osd/ceph-9: (2) No such file or directory^[[0m
```

```
/var/log/messages after i tried to start a ceph-disk via systemd:

Aug 30 16:41:24 localhost systemd: Starting Ceph disk activation: /dev/sdl10...
Aug 30 16:41:24 localhost sh: main_trigger: main_trigger: Namespace(cluster='ceph', dev='/dev/sdl10', dmcrypt=None, dmcrypt_key_dir='/etc/ceph/dmcrypt-keys', func=<function main_trigger at 0x14b7e60>, log_stdout=True, prepend_to_path='/usr/bin', prog='ceph-disk', setgroup=None, setuser=None, statedir='/var/lib/ceph', sync=True, sysconfdir='/etc/ceph', verbose=True)
Aug 30 16:41:24 localhost sh: command: Running command: /usr/sbin/init --version
Aug 30 16:41:24 localhost sh: command_check_call: Running command: /usr/bin/chown ceph:ceph /dev/sdl10
Aug 30 16:41:24 localhost sh: command: Running command: /usr/sbin/blkid -o udev -p /dev/sdl10
Aug 30 16:41:24 localhost sh: command: Running command: /usr/sbin/blkid -o udev -p /dev/sdl10
Aug 30 16:41:24 localhost sh: main_trigger: trigger /dev/sdl10 parttype 5ce17fce-4087-4169-b7ff-056cc58473f9 uuid 1f6271cb-b70b-4e21-96ff-a349f25b57b9
Aug 30 16:41:24 localhost sh: command: Running command: /usr/sbin/ceph-disk --verbose activate-block /dev/sdl10
Aug 30 16:41:24 localhost sh: main_trigger:
Aug 30 16:41:24 localhost sh: main_trigger: get_dm_uuid: get_dm_uuid /dev/sdl10 uuid path is /sys/dev/block/8:186/dm/uuid
Aug 30 16:41:24 localhost sh: command: Running command: /usr/sbin/blkid -o udev -p /dev/sdl10
Aug 30 16:41:24 localhost sh: command: Running command: /usr/bin/ceph-osd --get-device-fsid /dev/sdl10
Aug 30 16:41:24 localhost sh: Traceback (most recent call last):
Aug 30 16:41:24 localhost sh: File "/usr/sbin/ceph-disk", line 9, in <module>
Aug 30 16:41:24 localhost sh: load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
Aug 30 16:41:24 localhost sh: File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5704, in run
Aug 30 16:41:24 localhost sh: main(sys.argv[1:])
Aug 30 16:41:24 localhost sh: File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5655, in main
Aug 30 16:41:24 localhost sh: args.func(args)
Aug 30 16:41:24 localhost sh: File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5405, in <lambda>
Aug 30 16:41:24 localhost sh: func=lambda args: main_activate_space(name, args),
Aug 30 16:41:24 localhost sh: File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 4127, in main_activate_space
Aug 30 16:41:24 localhost sh: osd_uuid = get_space_osd_uuid(name, dev)
Aug 30 16:41:24 localhost sh: File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 4099, in get_space_osd_uuid
Aug 30 16:41:24 localhost sh: e,
Aug 30 16:41:24 localhost sh: ceph_disk.main.Error: Error: failed to get osd uuid/fsid from block: Command '/usr/bin/ceph-osd' returned non-zero exit status 1
Aug 30 16:41:24 localhost sh: Traceback (most recent call last):
Aug 30 16:41:24 localhost sh: File "/usr/sbin/ceph-disk", line 9, in <module>
Aug 30 16:41:24 localhost sh: load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
Aug 30 16:41:24 localhost sh: File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5704, in run
Aug 30 16:41:24 localhost sh: main(sys.argv[1:])
Aug 30 16:41:24 localhost sh: File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5655, in main
Aug 30 16:41:24 localhost sh: args.func(args)
Aug 30 16:41:24 localhost sh: File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 4858, in main_trigger
Aug 30 16:41:24 localhost sh: raise Error('return code ' + str(ret))
Aug 30 16:41:24 localhost sh: ceph_disk.main.Error: Error: return code 1
```

Any news how to fix this? All of my OSDs seem to be down ...
