### ISSUE TITLE
docker dedicated journals failing to prepare disks

### ISSUE THREAD

**Issue by andrewschoen** [ceph/ceph-ansible#1495]
The ``jewel-ansible2.2-docker_dedicated_journal`` scenario is failing with the following:

```
TASK [ceph-osd : prepare ceph osd disk] ****************************************
task path: /home/jenkins-build/build/workspace/ceph-ansible-prs-jewel-ansible2.2-docker_dedicated_journal/roles/ceph-osd/tasks/docker/start_docker_osd.yml:22
failed: [osd0] (item=[u'/dev/sda', {u'rc': 1, '_ansible_no_log': False, '_ansible_parsed': True, u'changed': True, 'failed': False, u'end': u'2017-05-03 15:11:05.162794', u'delta': u'0:00:00.009117', u'start': u'2017-05-03 15:11:05.153677', 'invocation': {u'module_args': {u'_raw_params': u"lsblk -o PARTLABEL /dev/sda | grep -sq 'ceph'", u'creates': None, u'chdir': None, u'warn': True, u'_uses_shell': True, u'executable': None, u'removes': None}, 'module_name': u'command'}, u'cmd': u"lsblk -o PARTLABEL /dev/sda | grep -sq 'ceph'", u'stdout': u'', 'failed_when_result': False, u'warnings': [], u'stderr': u'', 'item': u'/dev/sda', '_ansible_item_result': True, 'stdout_lines': []}]) => {
    "changed": true, 
    "cmd": "docker run --net=host --pid=host --privileged=true --name=\"ceph-osd-prepare-ceph-osd0-devdevsda\" -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -e \"OSD_DEVICE=/dev/sda\" -e \"OSD_JOURNAL_UUID=$(python -c \"import uuid; print uuid.uuid5(uuid.NAMESPACE_DNS, '1f4ba71f188249979178c9c6941491fd/dev/sda')\")\" -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE -e CLUSTER=test -e OSD_JOURNAL_SIZE=100 -e OSD_FORCE_ZAP=1 -e OSD_JOURNAL=/dev/sdb \"docker.io/ceph/daemon:tag-build-master-jewel-centos-7\"", 
    "delta": "0:00:08.738523", 
    "end": "2017-05-03 15:11:15.508596", 
    "failed": true, 
    "item": [
        "/dev/sda", 
        {
            "_ansible_item_result": true, 
            "_ansible_no_log": false, 
            "_ansible_parsed": true, 
            "changed": true, 
            "cmd": "lsblk -o PARTLABEL /dev/sda | grep -sq 'ceph'", 
            "delta": "0:00:00.009117", 
            "end": "2017-05-03 15:11:05.162794", 
            "failed": false, 
            "failed_when_result": false, 
            "invocation": {
                "module_args": {
                    "_raw_params": "lsblk -o PARTLABEL /dev/sda | grep -sq 'ceph'", 
                    "_uses_shell": true, 
                    "chdir": null, 
                    "creates": null, 
                    "executable": null, 
                    "removes": null, 
                    "warn": true
                }, 
                "module_name": "command"
            }, 
            "item": "/dev/sda", 
            "rc": 1, 
            "start": "2017-05-03 15:11:05.153677", 
            "stderr": "", 
            "stdout": "", 
            "stdout_lines": [], 
            "warnings": []
        }
    ], 
    "rc": 1, 
    "start": "2017-05-03 15:11:06.770073", 
    "warnings": []
}

STDOUT:

2017-05-03 15:11:08  /entrypoint.sh: static: does not generate config
HEALTH_ERR no osds
2017-05-03 15:11:08  /entrypoint.sh: It looks like /dev/sda isn't consistent, however OSD_FORCE_ZAP is enabled so we are zapping the device anyway
Creating new GPT entries.
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
Creating new GPT entries.
The operation has completed successfully.
Creating new GPT entries.
The operation has completed successfully.
The operation has completed successfully.


STDERR:

get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
zap: Zapping partition table on /dev/sda
command_check_call: Running command: /usr/sbin/sgdisk --zap-all -- /dev/sda
command_check_call: Running command: /usr/sbin/sgdisk --clear --mbrtogpt -- /dev/sda
update_partition: Calling partprobe on zapped device /dev/sda
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sda /usr/sbin/partprobe /dev/sda
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/ceph-osd --cluster=test --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster test --setuser ceph --setgroup ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster test --setuser ceph --setgroup ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster test --setuser ceph --setgroup ceph
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /usr/bin/ceph-osd --cluster=test --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=test --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=test --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=test --name=osd. --lookup osd_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
prepare_device: OSD will not be hot-swappable if journal is not the same device as the osd data
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
ptype_tobe_for_name: name = journal
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
command: Running command: /usr/sbin/parted --machine -- /dev/sdb print
get_free_partition_index: get_free_partition_index: analyzing 
                                                                          
BYT;
/dev/sdb:12.9GB:scsi:512:512:unknown:ATA QEMU HARDDISK:;

create_partition: Creating journal partition num 1 size 100 on /dev/sdb
command_check_call: Running command: /usr/sbin/sgdisk --new=1:0:+100M --change-name=1:ceph journal --partition-guid=1:58e5e4df-fa9b-518a-8d95-09ee59db8dc0 --typecode=1:45b0969e-9b03-4f30-b4c6-b4b80ceff106 --mbrtogpt -- /dev/sdb
update_partition: Calling partprobe on created device /dev/sdb
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdb /usr/sbin/partprobe /dev/sdb
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb1 uuid path is /sys/dev/block/8:17/dm/uuid
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/58e5e4df-fa9b-518a-8d95-09ee59db8dc0
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/58e5e4df-fa9b-518a-8d95-09ee59db8dc0
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
set_data_partition: Creating osd partition on /dev/sda
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
ptype_tobe_for_name: name = data
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
create_partition: Creating data partition num 1 size 0 on /dev/sda
command_check_call: Running command: /usr/sbin/sgdisk --largest-new=1 --change-name=1:ceph data --partition-guid=1:1866cc7f-1a53-4ea5-b762-98619c2640f6 --typecode=1:89c57f98-2fe5-4dc0-89c1-f3ad0ceff2be --mbrtogpt -- /dev/sda
update_partition: Calling partprobe on created device /dev/sda
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sda /usr/sbin/partprobe /dev/sda
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5047, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 4998, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1812, in main
    Prepare.factory(args).prepare()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1801, in prepare
    self.prepare_locked()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1832, in prepare_locked
    self.data.prepare(self.journal)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2494, in prepare
    self.prepare_device(*to_prepare_list)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2671, in prepare_device
    self.set_data_partition()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2598, in set_data_partition
    self.partition = self.create_data_partition()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2582, in create_data_partition
    return device.get_partition(partition_number)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1577, in get_partition
    dev = get_partition_dev(self.path, num)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 635, in get_partition_dev
    (pnum, dev))
ceph_disk.main.Error: Error: partition 1 for /dev/sda does not appear to exist
```

For a full log see: https://jenkins.ceph.com/job/ceph-ansible-prs-jewel-ansible2.2-docker_dedicated_journal/176/consoleFull

**Comment by andrewschoen** [comment]
This is related to https://github.com/ceph/ceph/pull/14275 which is a race condition that our CI exposes. It seems to happen most often on the jewel centos7 container.

**Comment by ktdreyer** [comment]
@leseb You can find the status of v10.2.8 by searching Redmine: http://tracker.ceph.com/projects/ceph-releases/search?q=v10.2.8

From [the release ticket](http://tracker.ceph.com/issues/19538) there, it could be next week, or it could be several weeks. I recommend asking smithfarm and yuriw in `#ceph-devel` for more details.

**Comment by leseb** [comment]
@ktdreyer thanks!

**Comment by djgalloway** [comment]
Could it hurt to add a `retries:` to that task?

**Comment by andrewschoen** [comment]
@djgalloway yeah, that might be a good approach until we get things backported. IIRC, @guits said it took 3 tries to get it working with his manual testing if he ran the ceph-disk command himself.

**Comment by leseb** [comment]
@andrewschoen @djgalloway is ceph-disk idempotent if half of the job is done?

**Comment by andrewschoen** [comment]
@leseb that I'm not positive about. I just remember @guits telling me he ran the ceph-disk command multiple times until it eventually worked.

**Comment by leseb** [comment]
@andrewschoen so the answer should be 'yes' I guess :). I'll check with @guits next Monday.
