### ISSUE TITLE
docker dmcrypt journal collocation is failing to prepare disks

### ISSUE THREAD

**Issue by andrewschoen** [ceph/ceph-ansible#1496]
The ``jewel-ansible2.2-docker_dmcrypt_journal_collocation`` scenario is failing with the following:

```
TASK [ceph-osd : prepare ceph osd disk] ****************************************
task path: /home/jenkins-build/build/workspace/ceph-ansible-prs-jewel-ansible2.2-docker_dmcrypt_journal_collocation/roles/ceph-osd/tasks/docker/start_docker_osd.yml:22
failed: [osd0] (item=[u'/dev/sda', {u'start': u'2017-05-03 15:10:21.048337', u'changed': True, u'end': u'2017-05-03 15:10:21.061002', '_ansible_no_log': False, u'warnings': [], 'stdout_lines': [], '_ansible_item_result': True, u'delta': u'0:00:00.012665', '_ansible_parsed': True, 'item': u'/dev/sda', 'failed': False, u'stderr': u'', u'rc': 1, 'invocation': {'module_name': u'command', u'module_args': {u'warn': True, u'creates': None, u'chdir': None, u'_raw_params': u"lsblk -o PARTLABEL /dev/sda | grep -sq 'ceph'", u'removes': None, u'executable': None, u'_uses_shell': True}}, u'cmd': u"lsblk -o PARTLABEL /dev/sda | grep -sq 'ceph'", 'failed_when_result': False, u'stdout': u''}]) => {
    "changed": true, 
    "cmd": "docker run --net=host --pid=host --privileged=true --name=\"ceph-osd-prepare-ceph-osd0-devdevsda\" -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -e \"OSD_DEVICE=/dev/sda\" -e \"OSD_JOURNAL_UUID=$(python -c \"import uuid; print uuid.uuid5(uuid.NAMESPACE_DNS, '6d337af465504a0d886c00231fc1adb8/dev/sda')\")\" -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE -e CLUSTER=ceph -e OSD_JOURNAL_SIZE=100 -e OSD_FORCE_ZAP=1 -e OSD_DMCRYPT=1 \"docker.io/ceph/daemon:tag-build-master-jewel-centos-7\"", 
    "delta": "0:00:07.420444", 
    "end": "2017-05-03 15:10:30.275585", 
    "failed": true, 
    "item": [
        "/dev/sda", 
        {
            "_ansible_item_result": true, 
            "_ansible_no_log": false, 
            "_ansible_parsed": true, 
            "changed": true, 
            "cmd": "lsblk -o PARTLABEL /dev/sda | grep -sq 'ceph'", 
            "delta": "0:00:00.012665", 
            "end": "2017-05-03 15:10:21.061002", 
            "failed": false, 
            "failed_when_result": false, 
            "invocation": {
                "module_args": {
                    "_raw_params": "lsblk -o PARTLABEL /dev/sda | grep -sq 'ceph'", 
                    "_uses_shell": true, 
                    "chdir": null, 
                    "creates": null, 
                    "executable": null, 
                    "removes": null, 
                    "warn": true
                }, 
                "module_name": "command"
            }, 
            "item": "/dev/sda", 
            "rc": 1, 
            "start": "2017-05-03 15:10:21.048337", 
            "stderr": "", 
            "stdout": "", 
            "stdout_lines": [], 
            "warnings": []
        }
    ], 
    "rc": 1, 
    "start": "2017-05-03 15:10:22.855141", 
    "warnings": []
}

STDOUT:

2017-05-03 15:10:24  /entrypoint.sh: static: does not generate config
HEALTH_ERR no osds
2017-05-03 15:10:24  /entrypoint.sh: It looks like /dev/sda isn't consistent, however OSD_FORCE_ZAP is enabled so we are zapping the device anyway
Creating new GPT entries.
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
Creating new GPT entries.
The operation has completed successfully.
2017-05-03 15:10:28  /entrypoint.sh: static: does not generate the admin key, so we can not get it.
2017-05-03 15:10:28  /entrypoint.sh: static: make it available with the help of your configuration management system.
2017-05-03 15:10:28  /entrypoint.sh: static: ceph-ansible is a good candidate to deploy a containerized version of Ceph.
2017-05-03 15:10:28  /entrypoint.sh: static: ceph-ansible will help you fetching the keys and push them on the right nodes.
2017-05-03 15:10:28  /entrypoint.sh: static: if you're interested, please visit: https://github.com/ceph/ceph-ansible
The operation has completed successfully.


STDERR:

get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
zap: Zapping partition table on /dev/sda
command_check_call: Running command: /usr/sbin/sgdisk --zap-all -- /dev/sda
command_check_call: Running command: /usr/sbin/sgdisk --clear --mbrtogpt -- /dev/sda
update_partition: Calling partprobe on zapped device /dev/sda
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sda /usr/sbin/partprobe /dev/sda
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph --setuser ceph --setgroup ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph --setuser ceph --setgroup ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph --setuser ceph --setgroup ceph
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
set_type: Will colocate journal with data on /dev/sda
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
set_or_create_partition: Creating osd partition on /dev/sda
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
ptype_tobe_for_name: name = lockbox
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
create_partition: Creating lockbox partition num 3 size 10 on /dev/sda
command_check_call: Running command: /usr/sbin/sgdisk --new=3:0:+10M --change-name=3:ceph lockbox --partition-guid=3:01066f89-9c58-440e-bea7-ded1d148de47 --typecode=3:fb3aabf9-d25f-47cc-bf5e-721d181642be --mbrtogpt -- /dev/sda
update_partition: Calling partprobe on created device /dev/sda
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sda /usr/sbin/partprobe /dev/sda
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda3 uuid path is /sys/dev/block/8:3/dm/uuid
populate: Creating lockbox fs on %s: mkfs -t ext4 /dev/sda3
command_check_call: Running command: /usr/sbin/mkfs -t ext4 /dev/sda3
mkfs.ext4: No such file or directory
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5047, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 4998, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1812, in main
    Prepare.factory(args).prepare()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1801, in prepare
    self.prepare_locked()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1831, in prepare_locked
    self.lockbox.prepare()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2408, in prepare
    self.populate()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2346, in populate
    command_check_call(args)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 446, in command_check_call
    return subprocess.check_call(arguments)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/sbin/mkfs', '-t', 'ext4', '/dev/sda3']' returned non-zero exit status 1
```

For a full log see: https://jenkins.ceph.com/job/ceph-ansible-prs-jewel-ansible2.2-docker_dmcrypt_journal_collocation/171/consoleFull

**Comment by andrewschoen** [comment]
This seems to occur only on the ``tag-build-master-luminous-centos-7`` container, not ``tag-build-master-luminous-ubuntu-16.04``.

**Comment by leseb** [comment]
`mkfs.ext4: No such file or directory`, weird.

**Comment by leseb** [comment]
@andrewschoen This should be relatively easy to fix. Are we still experiencing this?

**Comment by andrewschoen** [comment]
@leseb we're not seeing it in the upstream CI after I switched to the jewel container in #1501

This does happen consistently with the centos7 container and in the downstream CI.

**Comment by leseb** [comment]
@andrewschoen, indeed downstream is also missing e2fsprogs which provides mfs.ext4, we have two solutions:

* add e2fsprogs into the base image (difficult)
* install e2fsprogs during build time (this assumes our rhcs repos have e2fsprogs, I doubt).

@ktdreyer thoughts?

**Comment by ktdreyer** [comment]
`e2fsprogs` is in RHEL ([access.redhat.com/downloads](https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.3/x86_64/packages) has the authoritative  full list of RHEL packages)

**Comment by leseb** [comment]
Thanks @ktdreyer, adding `e2fsprogs` to rhel images then.
