### ISSUE TITLE
luminous : ganesha.nfsd : 1 validation errors in block FSAL

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#1994]
Hello,

I'm testing nfs/rgw access but I have a issue with ganesha 

ganesha config : [ganesha.conf.txt](https://github.com/ceph/ceph-ansible/files/1359209/ganesha.conf.txt)

and I got this error in ganesha.log :

```
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] create_export :FSAL :CRIT :Unable to read Ceph configuration for /.
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] mdcache_fsal_create_export :FSAL :MAJ :Failed to call create_export on underlying FSAL Ceph
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/cephobject) to (/)
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] main :NFS STARTUP :WARN :No export entries found in configuration file !!!
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:19): 1 validation errors in block FSAL
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:19): Errors processing block (FSAL)
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:3): 1 validation errors in block EXPORT
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:3): Errors processing block (EXPORT)
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:42): Failed to initialize FSAL (RGW)
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:42): 1 validation errors in block FSAL
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:42): Errors processing block (FSAL)
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:26): 1 validation errors in block EXPORT
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:26): Errors processing block (EXPORT)
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] lower_my_caps :NFS STARTUP :EVENT :CAP_SYS_RESOURCE was successfully removed for proper quota management in FSAL
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] lower_my_caps :NFS STARTUP :EVENT :currenty set capabilities are: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap+ep
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_Init_admin_thread :NFS CB :EVENT :Admin thread initialized
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs4_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_rpc_cb_init_ccache :NFS STARTUP :WARN :gssd_refresh_krb5_machine_credential failed (-3:111)
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_Start_threads :THREAD :EVENT :Starting delayed executor.
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_Start_threads :THREAD :EVENT :gsh_dbusthread was started successfully
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_Start_threads :THREAD :EVENT :admin thread was started successfully
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_Start_threads :THREAD :EVENT :reaper thread was started successfully
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_Start_threads :THREAD :EVENT :General fridge was started successfully
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[reaper] nfs_in_grace :STATE :EVENT :NFS Server Now IN GRACE
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nsm_connect :NLM :CRIT :failed to connect to statd
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nsm_unmonitor_all :NLM :CRIT :Can not unmonitor all clnt_create returned NULL
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
29/09/2017 11:36:47 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
29/09/2017 11:38:17 : epoch 59ce142f : iccluster023 : ganesha.nfsd-1905[reaper] nfs_in_grace :STATE :EVENT :NFS Server Now NOT IN GRACE
```

Yoann

**Comment by leseb** [comment]
@jprovaznik can you please look into this?

**Comment by leseb** [comment]
@alimaredia also please look into this, thanks

**Comment by alimaredia** [comment]
@mistur Your ganesha.conf file is not configured correctly. Each `EXPORT` block should have a different Export_id number. Also if you're just testing the RGW FSAL then it is best to have `nfs_file_gw` set to `false` so that the `EXPORT` block for the ceph fsal isn't included in the ganesha.conf generated by ansible.

**Comment by mistur** [comment]
Hello,

my `ganesha.conf` has been fully generated by ceph-ansible. actually I'm testing lot's of feature with luminous so I have activated lots of stuff in my playbook, I might try `nfs_file_gw` later.

I guess if both `nfs_rgw_gw` and `nfs_file_gw` are activated, 2 differents id should be set, shouldn't they ?

I have comment the CEPH FSAL and I don't have error in the `ganesha.log`

```
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] lower_my_caps :NFS STARTUP :EVENT :CAP_SYS_RESOURCE was successfully removed for proper quota management in FSAL
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] lower_my_caps :NFS STARTUP :EVENT :currenty set capabilities are: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap+ep
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_Init_admin_thread :NFS CB :EVENT :Admin thread initialized
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs4_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_rpc_cb_init_ccache :NFS STARTUP :EVENT :Callback creds directory (/var/run/ganesha) already exists
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_rpc_cb_init_ccache :NFS STARTUP :WARN :gssd_refresh_krb5_machine_credential failed (-1765328160:0)
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_Start_threads :THREAD :EVENT :Starting delayed executor.
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_Start_threads :THREAD :EVENT :gsh_dbusthread was started successfully
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_Start_threads :THREAD :EVENT :admin thread was started successfully
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_Start_threads :THREAD :EVENT :reaper thread was started successfully
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_Start_threads :THREAD :EVENT :General fridge was started successfully
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[reaper] nfs_in_grace :STATE :EVENT :NFS Server Now IN GRACE
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nsm_connect :NLM :CRIT :failed to connect to statd
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nsm_unmonitor_all :NLM :CRIT :Can not unmonitor all clnt_create returned NULL
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
05/10/2017 18:54:48 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
05/10/2017 18:56:18 : epoch 59d663d8 : iccluster019 : ganesha.nfsd-80864[reaper] nfs_in_grace :STATE :EVENT :NFS Server Now NOT IN GRACE
```

**Comment by alimaredia** [comment]
This is the template file for the `ganesha.conf` https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-nfs/templates/ganesha.conf.j2. The variables there are defined in `group_vars/nfss.yml` should be changed so that both Export_ids are different. 

You are able to make those changes to the configuration by hand, but I issued https://github.com/ceph/ceph-ansible/pull/2005 so that both FSALs work at the same time out of the box. 

I don't quite follow the last part of you message. Did you set nfs_file_gw to false, removing the first `EXPORT` block shown in your ganesha.conf?

**Comment by mistur** [comment]
Actually, I have just commented manually the `nfs_file_gw` section because of https://github.com/ceph/ceph-ansible/issues/1981. I can try to downgrade ansible if need.

I will test this as soon as I can

**Comment by mistur** [comment]
Hello,

I have retried to run the playbook from a fresh install of ubuntu Xenial with ansible 2.3.2. meanwhile, I found an error in my config into all.yml 

```
root@ntxvm019:~/ceph-ansible# ansible-playbook --version
ansible-playbook 2.3.2.0
  config file = /root/ceph-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

Here the error in my config : 

```
diff --git a/ceph-config/cluster-luminous/group_vars/all.yml b/ceph-config/cluster-luminous/group_vars/all.yml
index b298fb4..020024b 100644
--- a/ceph-config/cluster-luminous/group_vars/all.yml
+++ b/ceph-config/cluster-luminous/group_vars/all.yml
@@ -354,8 +354,8 @@ radosgw_civetweb_options: "num_threads={{ radosgw_civetweb_num_threads }}"
 # Eg. If you want to specify for each radosgw node which address the radosgw will bind to you can set it in your **inventory host file** by using 'radosgw_address' variable.
 # Preference will go to radosgw_address if both radosgw_address and radosgw_interface are defined.
 # To use an IPv6 address, use the radosgw_address setting instead (and set ip_version to ipv6)
-radosgw_interface: localhost
-#radosgw_address: 0.0.0.0
+#radosgw_interface: interface
+radosgw_address: 127.0.0.1
 #radosgw_address_block: []
 radosgw_keystone: false # activate OpenStack Keystone options full detail here: http://ceph.com/docs/master/radosgw/keystone/
 # Rados Gateway options
```

and now, I have this error (this error in none fatal, the playbook continues to run after) : 

```
TASK [ceph-config : generate ceph configuration file: luminous.conf] ****************************************************************************************************************************************************************************************************************************************************
task path: /root/ceph-ansible/roles/ceph-config/tasks/main.yml:30
<iccluster007.iccluster.epfl.ch> ESTABLISH SSH CONNECTION FOR USER: None
<iccluster007.iccluster.epfl.ch> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r-%p iccluster007.iccluster.epfl.ch '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<iccluster007.iccluster.epfl.ch> (0, '/root\n', '')
<iccluster007.iccluster.epfl.ch> ESTABLISH SSH CONNECTION FOR USER: None
<iccluster007.iccluster.epfl.ch> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r-%p iccluster007.iccluster.epfl.ch '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1507279132.67-97088057295286 `" && echo ansible-tmp-1507279132.67-97088057295286="` echo /root/.ansible/tmp/ansible-tmp-1507279132.67-97088057295286 `" ) && sleep 0'"'"''
<iccluster015.iccluster.epfl.ch> ESTABLISH SSH CONNECTION FOR USER: None
<iccluster015.iccluster.epfl.ch> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r-%p iccluster015.iccluster.epfl.ch '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<iccluster007.iccluster.epfl.ch> (0, 'ansible-tmp-1507279132.67-97088057295286=/root/.ansible/tmp/ansible-tmp-1507279132.67-97088057295286\n', '')
[DEPRECATION WARNING]: ansible.utils.unicode.to_bytes is deprecated.  Use ansible.module_utils._text.to_bytes instead.
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
<iccluster015.iccluster.epfl.ch> (0, '/root\n', '')
<iccluster015.iccluster.epfl.ch> ESTABLISH SSH CONNECTION FOR USER: None
<iccluster015.iccluster.epfl.ch> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r-%p iccluster015.iccluster.epfl.ch '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1507279132.71-204547199261695 `" && echo ansible-tmp-1507279132.71-204547199261695="` echo /root/.ansible/tmp/ansible-tmp-1507279132.71-204547199261695 `" ) && sleep 0'"'"''
[DEPRECATION WARNING]: ansible.utils.unicode.to_unicode is deprecated.  Use ansible.module_utils._text.to_text instead.
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
<iccluster019.iccluster.epfl.ch> ESTABLISH SSH CONNECTION FOR USER: None
<iccluster019.iccluster.epfl.ch> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r-%p iccluster019.iccluster.epfl.ch '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<iccluster015.iccluster.epfl.ch> (0, 'ansible-tmp-1507279132.71-204547199261695=/root/.ansible/tmp/ansible-tmp-1507279132.71-204547199261695\n', '')
[DEPRECATION WARNING]: ansible.utils.unicode.to_bytes is deprecated.  Use ansible.module_utils._text.to_bytes instead.
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ansible.utils.unicode.to_unicode is deprecated.  Use ansible.module_utils._text.to_text instead.
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
<iccluster019.iccluster.epfl.ch> (0, '/root\n', '')
<iccluster019.iccluster.epfl.ch> ESTABLISH SSH CONNECTION FOR USER: None
<iccluster019.iccluster.epfl.ch> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r-%p iccluster019.iccluster.epfl.ch '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1507279132.76-24065710489358 `" && echo ansible-tmp-1507279132.76-24065710489358="` echo /root/.ansible/tmp/ansible-tmp-1507279132.76-24065710489358 `" ) && sleep 0'"'"''
<iccluster019.iccluster.epfl.ch> (0, 'ansible-tmp-1507279132.76-24065710489358=/root/.ansible/tmp/ansible-tmp-1507279132.76-24065710489358\n', '')
[DEPRECATION WARNING]: ansible.utils.unicode.to_bytes is deprecated.  Use ansible.module_utils._text.to_bytes instead.
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ansible.utils.unicode.to_unicode is deprecated.  Use ansible.module_utils._text.to_text instead.
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 522, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ceph-ansible/plugins/actions/_v2_config_template.py", line 521, in run
    convert_data=False
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 437, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 659, in do_template
    res = j2_concat(rf)
  File "<template>", line 467, in root
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 170, in get_source
    filename = path.join(searchpath, *pieces)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'list' object has no attribute 'endswith'

fatal: [iccluster007.iccluster.epfl.ch]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
