### ISSUE TITLE
ImportError: cannot import name to_bytes

### ISSUE THREAD

**Issue by Futvin** [ceph/ceph-ansible#2474]
I ran into this error while running ansible 2.5.0 on task *TASK [ceph-config : create ceph conf directory]*

I "fixed" this by updating ./ceph-ansible/plugins/actions/_v2_config_template.py

In the imports I commented out the offending line, and replaced it with two lines that work for ansible 2.5

#from ansible.utils.unicode import to_bytes, to_unicode
from ansible.module_utils._text import to_text as to_unicode
from ansible.module_utils._text import to_bytes

**Comment by Asher256** [comment]
Same here.
```
Traceback (most recent call last):
  File "/var/lib/ceph-ansible/.pyenv_ansible/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/var/lib/ceph-ansible/.pyenv_ansible/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/var/lib/ceph-ansible/.pyenv_ansible/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 159, in run
    result = self._tqm.run(play=play)
  File "/var/lib/ceph-ansible/.pyenv_ansible/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 290, in run
    play_return = strategy.run(iterator, play_context)
  File "/var/lib/ceph-ansible/.pyenv_ansible/local/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 217, in run
    action = action_loader.get(task.action, class_only=True)
  File "/var/lib/ceph-ansible/.pyenv_ansible/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 370, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/var/lib/ceph-ansible/.pyenv_ansible/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 346, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/var/lib/jenkins/workspace/deploy-ceph/plugins/actions/config_template.py", line 29, in <module>
    from _v2_config_template import *
  File "/var/lib/jenkins/workspace/deploy-ceph/plugins/actions/_v2_config_template.py", line 37, in <module>
    from ansible.utils.unicode import to_bytes, to_unicode
ImportError: cannot import name to_bytes
```

This bug happens with ansible version 2.5.0 (it works very well with Ansible 2.4.x).

**Comment by guits** [comment]
it will be addressed by #2475
