### ISSUE TITLE
The error was: TypeError: cannot deepcopy this pattern object

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#2672]
This this issue on mimic

http://qa-proxy.ceph.com/teuthology/teuthology-2018-05-25_05:15:02-ceph-ansible-mimic-distro-basic-ovh/2586503/teuthology.log

"""
2018-05-29T16:12:39.001 INFO:teuthology.orchestra.run.ovh085.stdout:TASK [ceph-validate : validate provided configuration] *************************
2018-05-29T16:12:39.001 INFO:teuthology.orchestra.run.ovh085.stdout:task path: /home/ubuntu/ceph-ansible/roles/ceph-validate/tasks/main.yml:2
2018-05-29T16:12:39.001 INFO:teuthology.orchestra.run.ovh085.stdout:Tuesday 29 May 2018  16:12:38 +0000 (0:00:03.459)       0:00:16.619 ***********
2018-05-29T16:12:39.517 INFO:teuthology.orchestra.run.ovh085.stdout:An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: cannot deepcopy this pattern object
2018-05-29T16:12:39.518 INFO:teuthology.orchestra.run.ovh085.stdout:fatal: [ovh085.front.sepia.ceph.com]: FAILED! => {
2018-05-29T16:12:39.518 INFO:teuthology.orchestra.run.ovh085.stdout:    "failed": true
2018-05-29T16:12:39.518 INFO:teuthology.orchestra.run.ovh085.stdout:}
2018-05-29T16:12:39.518 INFO:teuthology.orchestra.run.ovh085.stdout:
2018-05-29T16:12:39.518 INFO:teuthology.orchestra.run.ovh085.stdout:MSG:
2018-05-29T16:12:39.518 INFO:teuthology.orchestra.run.ovh085.stdout:
2018-05-29T16:12:39.518 INFO:teuthology.orchestra.run.ovh085.stdout:Unexpected failure during module execution.
2018-05-29T16:12:39.706 INFO:teuthology.orchestra.run.ovh085.stdout:An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: cannot deepcopy this pattern object
2018-05-29T16:12:39.706 INFO:teuthology.orchestra.run.ovh085.stdout:fatal: [ovh063.front.sepia.ceph.com]: FAILED! => {
2018-05-29T16:12:39.706 INFO:teuthology.orchestra.run.ovh085.stdout:    "failed": true
2018-05-29T16:12:39.706 INFO:teuthology.orchestra.run.ovh085.stdout:}
2018-05-29T16:12:39.706 INFO:teuthology.orchestra.run.ovh085.stdout:
2018-05-29T16:12:39.707 INFO:teuthology.orchestra.run.ovh085.stdout:MSG:
2018-05-29T16:12:39.707 INFO:teuthology.orchestra.run.ovh085.stdout:
2018-05-29T16:12:39.707 INFO:teuthology.orchestra.run.ovh085.stdout:Unexpected failure during module execution.
2018-05-29T16:12:39.769 INFO:teuthology.orchestra.run.ovh085.stdout:An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: cannot deepcopy this pattern object

"""

**Comment by guits** [comment]
@vasukulkarni could be helpful to have the full python trace, any chance you could run your test with `-vvv` so we can catch it?

**Comment by alfredodeza** [comment]
I think that something in Ansible is adding a code object that cannot be serialized. It is not possible to tell what that object may be. I think that the initial loading of the schema engine should be caught to allow execution to continue in the case of exceptions.

The bigger issue is how to deal with dictionaries that have non-serializable information in them. Should the validation engine avoid the deepcopy in that case (with the caveat of polluting the incoming object), or have an extra step for pruning non-serializable objects?

    Traceback (most recent call last):
      File "/tmp/tox.GNbAEokeuM/ansible2.3-nightly_centos7/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
        res = self._execute()
      File "/tmp/tox.GNbAEokeuM/ansible2.3-nightly_centos7/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 522, in _execute
        result = self._handler.run(task_vars=variables)
      File "/tmp/tox.GNbAEokeuM/ansible2.3-nightly_centos7/tmp/ceph-ansible/plugins/actions/validate.py", line 43, in run
        notario.validate(host_vars, install_options, defined_keys=True)
      File "/tmp/tox.GNbAEokeuM/ansible2.3-nightly_centos7/lib/python2.7/site-packages/notario/engine.py", line 343, in validate
        validator = Validator(data, schema, defined_keys=defined_keys)
      File "/tmp/tox.GNbAEokeuM/ansible2.3-nightly_centos7/lib/python2.7/site-packages/notario/engine.py", line 14, in __init__
        self.data = Data(data, schema).normalized()
      File "/tmp/tox.GNbAEokeuM/ansible2.3-nightly_centos7/lib/python2.7/site-packages/notario/normal.py", line 8, in __init__
        self.raw_data = copy.deepcopy(data)
      File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib64/python2.7/copy.py", line 174, in deepcopy
        y = copier(memo)
    TypeError: cannot deepcopy this pattern object
