### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/home/centos/.ansible/tmp/ansible-tmp-xxxx/source'

### ISSUE THREAD

**Issue by patsevanton** [ceph/ceph-ansible#3193]
2. Did you already search the existing open issues for anything similar? -->
Yes

**Bug Report**

What happened:
Run ansible-playbook on ubuntu 18.04.
Servers is Centos 7
ansible-playbook -u centos -i inventory/hosts -b --diff site.yml -vvv  -e "ansible_ssh_private_key_file=/home/user/key.pem"

TASK [ceph-config : generate ceph configuration file: ceph.conf] ********************************************************************************
task path: /home/user/kubernetes/ceph-ansible/roles/ceph-config/tasks/main.yml:12
```

(0, '\n{"invocation": {"module_args": {"directory_mode": null, "force": false, "remote_src": null, "_original_basename": null, "path": "/etc/ceph/ceph.conf", "owner": null, "follow": true, "group": null, "unsafe_writes": null, "serole": null, "content": null, "state": "file", "setype": null, "selevel": null, "regexp": null, "src": null, "seuser": null, "recurse": false, "_diff_peek": "True", "delimiter": null, "mode": null, "attributes": null, "backup": null}}, "path": "/etc/ceph/ceph.conf", "state": "absent", "changed": false, "appears_binary": false}\n', '')
The full traceback is:
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/home/user/.local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 584, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/user/kubernetes/ceph-ansible/plugins/actions/_v2_config_template.py", line 660, in run
    transferred_data, task_vars))
  File "/home/user/.local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 1017, in _get_diff_data
    st = os.stat(source)
OSError: [Errno 2] No such file or directory: '/home/centos/.ansible/tmp/ansible-tmp-1538629954.15-118487997636247/source'

fatal: [test-tools-ceph-apatsev-2.russianpost.ru]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```
Share your group_vars files, inventory
cat inventory/group_vars/all.yml 
```
ceph_origin: repository
ceph_repository: community
ceph_repository_type: cdn
ceph_stable_release: luminous
public_network: xx.yy.zz.0/24
cluster_network: xx.yy.zz.0/24
osd_objectstore: bluestore
osd_scenario: collocated
devices:
 - /dev/vdb
osd_pool_default_pg_num: 30

ceph_conf_overrides:
  global:
    "osd journal size": 1024
    "osd pool default size": 3
    "osd pool default min size": 3

```
cat inventory/hosts 
```
[mons]
test-ceph-1.local monitor_address=xx.yy.zz.172
test-ceph-2.local monitor_address=xx.yy.zz.175
test-ceph-3.local monitor_address=xx.yy.zz.173

[osds]
test-ceph-1.local
test-ceph-2.local
test-ceph-3.local

[mgrs]
test-ceph-1.local
test-ceph-2.local
test-ceph-3.local

[mdss]
test-ceph-1.local
test-ceph-2.local
test-ceph-3.local
```

**Environment**:
* OS (e.g. from /etc/os-release):
cat /etc/os-release
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

* Kernel (e.g. `uname -a`):
Linux test-tools-ceph-apatsev-2 3.10.0-514.26.1.el7.x86_64 #1 SMP Thu Jun 29 16:05:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`):
-bash: docker: command not found

* Ansible version (e.g. `ansible-playbook --version`):
```
ansible-playbook 2.6.4
  config file = /home/user/kubernetes/ceph-ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python2.7/site-packages/ansible
  executable location = /home/user/.local/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```
* ceph-ansible version (e.g. `git head or tag or stable branch`):
stable-3.1 
* Ceph version (e.g. `ceph -v`):
ceph version 12.2.8 (ae699615bac534ea496ee965ac6192cb7e0e07c0) luminous (stable)

**Comment by leseb** [comment]
Looks like an Ansible error to me, did you try to run that multiple times? Thanks

**Comment by patsevanton** [comment]
I think problem in my notebook.
run pip install -r requirements.txt
output segmentation fault
Sorry
