### ISSUE TITLE
Variable validation fails for `dedicated_devices` if it's a combination of lists

### ISSUE THREAD

**Issue by mnarusze** [ceph/ceph-ansible#3247]
**Bug Report**

**What happened:**

I tested following scenarios:
1)
```
devices:
  - /dev/loop0
  - /dev/loop1
  - /dev/loop2
  - /dev/loop3
dedicated_devices:
  - /dev/loop4
  - /dev/loop5
  - /dev/loop6
  - /dev/loop7
```
2)
```
some_disks:
  - /dev/loop0
  - /dev/loop1
  - /dev/loop2
  - /dev/loop3
some_other_disks:
  - /dev/loop4
  - /dev/loop5
  - /dev/loop6
  - /dev/loop7
devices: "{{ some_disks }}"
dedicated_devices: "{{ some_other_disks }}"
```
3)
```
some_disks:
  - /dev/loop0
  - /dev/loop1
  - /dev/loop2
  - /dev/loop3
  - /dev/loop4
  - /dev/loop5
some_other_disks:
  - /dev/loop6
  - /dev/loop7
devices: "{{ some_disks[0:4] }}"
dedicated_devices: "{{ some_disks[4:6] + some_other_disks }}"
```

1) and 2) work without issues, 3) fails for every OSD with the following message:
```
TASK [ceph-validate : validate provided configuration] **************************************************
task path: /home/mnarusze/ceph/ceph-ansible/roles/ceph-validate/tasks/main.yml:2
Friday 19 October 2018  08:11:29 +0000 (0:00:00.667)       0:00:39.164 ********
 [ERROR]: [ceph-osd-1] Validation failed for variable: dedicated_devices

The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 584, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/mnarusze/ceph/ceph-ansible/plugins/actions/validate.py", line 99, in run
    given = "[{}] Given value for {}: {}".format(host, error.path[0], error.path[1])
IndexError: list index out of range

fatal: [ceph-osd-1]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**What you expected to happen:**

I expect all scenarios to work

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.5.1804
* Kernel (e.g. `uname -a`): 3.10.0-693
* Ansible version (e.g. `ansible-playbook --version`): 2.6.5
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-3.2
* Ceph version (e.g. `ceph -v`): luminous

**Comment by guits** [comment]
should be fixed by #3210

**Comment by mnarusze** [comment]
I have just tested another scenario and it seems that ceph-validator is really weak with more complex variables. Example:

tc1.yml that's added with `--extra-vars @tc1.yml`:
```
test_case:
  devices: "{{ some_drives }} + {{ some_more_drives }}"
  dedicated_devices: []
  osd_scenario: collocated
  osd_objectstore: bluestore
```
group_vars/osds.yml:
```
devices: "{{ test_case.devices|default([]) }}"
dedicated_devices: "{{ test_case.dedicated_devices|default([]) }}"
osd_scenario: "{{ test_case.osd_scenario|default('') }}"
osd_objectstore: "{{ test_case.osd_objectstore|default('') }}"
```

validation error:
```
 [ERROR]: [ceph-osd-1] Validation failed for variable: osd_objectstore                                                                                                                                         
                                                                                                                                                                                                                  
 [ERROR]: [ceph-osd-1] Given value for osd_objectstore: {{ test_case.osd_objectstore|default('') }}                                                                                                            
                                                                                                                                                                                                                  
 [ERROR]: [ceph-osd-1] Reason: osd_objectstore must be either 'bluestore' or 'filestore'                                                                                                                       
                                                                                                                                                                                                                  
fatal: [ceph-osd-1]: FAILED! => {                                                                                                                                                                                 
    "changed": false,                                                                                                                                                                                             
    "msg": "[ceph-osd-1] Validation failed for variable: osd_objectstore\n[ceph-osd-1] Reason: osd_objectstore must be either 'bluestore' or 'filestore'\n[ceph-osd-1] Given value for osd_objectstore: {{
 test_case.osd_objectstore|default('') }}",                                                                                                                                                                       
    "stderr_lines": [                                                                                                                                                                                             
        "[ceph-osd-1] Validation failed for variable: osd_objectstore"                                                                                                                                         
    ]                                                                                                                                                                                                             
} 
```

As a result, I'm not even sure if the fix mentioned above will be enough

**Comment by leseb** [comment]
@andrewschoen do you mind looking into this? Thanks.

**Comment by rishabh-d-dave** [comment]
Code in this commit fixes that issue. I've discussion on this pending with Andrew Schoen.

**Comment by rishabh-d-dave** [comment]
I've  a patch ready. I'll raise a PR  soon so that we can resolve this issue irrespective of Ansible's decision .

**Comment by rishabh-d-dave** [comment]
Raised a PR for this issue yesterday - https://github.com/ceph/ceph-ansible/pull/3326.

**Comment by rishabh-d-dave** [comment]
Closing this issue since #3326 fixes it.
