### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zygis** [ceph/ceph-ansible#3499]
**Bug Report**

What happened:
Tried to do first steps with ceph-ansible
The first error is `The error was: KeyError: 'containerized_deployment'`
After uncommenting line `containerized_deployment: False` in `group_vars/all.yml` I receive next error: `IndexError: list index out of range` which says nothing about what isn't right
Executing with `-vvv` gives:
```The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 584, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ceph-ansible/plugins/actions/validate.py", line 100, in run
    msg = "[{}] Validation failed for variable: {}".format(host, error.path[0])
IndexError: list index out of range

fatal: [192.168.83.11]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

`ceph-ansible/plugins/actions/validate.py` is stuck at `notario.validate(host_vars, install_options, defined_keys=True)`
What you expected to happen:
I expect to receive a proper error with a variable name which should be defined or fixed
How to reproduce it (minimal and precise):
Clone repository. Checkout branch stable-3.2. `cp group_vars/all.yml.sample group_vars/all.yml` uncomment line `containerized_deployment: False`. Execute site.yml playbook
Share your group_vars files, inventory
```
cat group_vars/all.yml | grep -v -e ^# | grep -v -e ^$
---
dummy:
containerized_deployment: False
```
```
cat office.ini
[mons]

192.168.83.11
192.168.83.12
192.168.83.13

[osds]

192.168.83.21
192.168.83.22
192.168.83.23

[ceph:children]
mons
osds

[all:vars]
ansible_user=root
```

**Environment**:
* OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
* Kernel (e.g. `uname -a`):
```
Linux test-ansible 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100) x86_64 x86_64 x86_64 GNU/Linux
```
* Docker version if applicable (e.g. `docker version`): -
* Ansible version (e.g. `ansible-playbook --version`):
```
ansible-playbook 2.6.11
  config file = /root/ceph-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```
* ceph-ansible version (e.g. `git head or tag or stable branch`):
```
git log
commit 4e94d11aa738a0f5de3e84dc70d534fbe9c34c2f (HEAD -> stable-3.2, tag: v3.2.2, origin/stable-3.2)
Author: Rishabh Dave <ridave@redhat.com>
Date:   Wed Jan 9 21:07:00 2019 +0530
```
* Ceph version (e.g. `ceph -v`): -

**Comment by zygis** [comment]
Nevermind. Site.yml was from the wrong branch...
