### ISSUE TITLE
LVM ceph-ansible/plugins/actions/validate.py", line 103, in run

### ISSUE THREAD

**Issue by snoopel** [ceph/ceph-ansible#3878]
What happened:
I want to use the lvm osd_screnario with osd_auto_discovery

What you expected to happen:
if i work with the normal bluestore settings, the ansible-run works without problems. now i want to switch my existing osd from ceph-disk to ceph-volume (lvm). 

```
cat group_vars/osds.yml | grep -v -e ^# | grep -v -e ^$
---
dummy:
osd_auto_discovery: true
osd_screnario: lvm
```

I receive the following error message

```
TASK [ceph-validate : validate provided configuration] *****************************************************************************************************************************************************
task path: /root/ceph-ansible/roles/ceph-validate/tasks/main.yml:2
Thursday 18 April 2019  08:23:11 +0200 (0:00:00.240)       0:00:11.955 ******** 
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 576, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ceph-ansible/plugins/actions/validate.py", line 103, in run
    msg = "[{}] Validation failed for variable: {}".format(host, error.path[0])
IndexError: list index out of range

fatal: [10.253.91.131]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
```
cat  /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

* Kernel (e.g. `uname -a`):
`Linux dev-ceph 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
```
ansible-playbook --version
ansible-playbook 2.6.0
  config file = /root/ceph-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

* ceph-ansible version (e.g. `git head or tag or stable branch`):
```
git branch
* (HEAD detached at v3.2.12)
```

* Ceph version (e.g. `ceph -v`):
```
ceph -v
ceph version 12.2.11 (26dc3775efc7bb286a1d6d66faee0ba30ea23eee) luminous (stable)
```

**Comment by wesleysutton** [comment]
I got the same error. Here's how I fixed it:

```
diff --git a/plugins/actions/validate.py b/plugins/actions/validate.py
index 79fc941..1c76a59 100644
--- a/plugins/actions/validate.py
+++ b/plugins/actions/validate.py
@@ -100,7 +100,8 @@ class ActionModule(ActionBase):
 
         except Invalid as error:
             display.vvvv("Notario Failure: %s" % str(error))
-            msg = "[{}] Validation failed for variable: {}".format(host, error.path[0])
+            given = ""
+            msg = "[{}] Validation failed for variable: {}".format(host, error)
             display.error(msg)
             reason = "[{}] Reason: {}".format(host, error.reason)
             try:
```
