### ISSUE TITLE
inject grafana dashboard layouts

### ISSUE THREAD

**Issue by Snegohod** [ceph/ceph-ansible#4565]
**Bug Report**

What happened:
> TASK [ceph-dashboard : inject grafana dashboard layouts] *******************************************************************************
> Tuesday 08 October 2019  10:17:32 +0300 (0:00:02.450)       1:01:36.587 *******
> fatal: [node1.internet.nio2 -> node1.internet.nio2]: FAILED! => changed=false
>   cmd:
>   - docker
>   - exec
>   - ceph-mon-node1
>   - ceph
>   - --cluster
>   - ceph-ovirt
>   - dashboard
>   - grafana
>   - dashboards
>   - update
>   delta: '0:00:04.417061'
>   end: '2019-10-08 10:21:23.070323'
>   msg: non-zero return code
>   rc: 22
>   start: '2019-10-08 10:21:18.653262'
>   stderr: |-
>     Error EINVAL: Traceback (most recent call last):
>       File "/usr/share/ceph/mgr/mgr_module.py", line 914, in _handle_command
>         return self.handle_command(inbuf, cmd)
>       File "/usr/share/ceph/mgr/dashboard/module.py", line 450, in handle_command
>         push_local_dashboards()
>       File "/usr/share/ceph/mgr/dashboard/grafana.py", line 132, in push_local_dashboards
>         retry()
>       File "/usr/share/ceph/mgr/dashboard/grafana.py", line 89, in __call__
>         result = self.func(*self.args, **self.kwargs)
>       File "/usr/share/ceph/mgr/dashboard/grafana.py", line 127, in push
>         grafana.push_dashboard(body)
>       File "/usr/share/ceph/mgr/dashboard/grafana.py", line 54, in push_dashboard
>         response.raise_for_status()
>       File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
>         raise HTTPError(http_error_msg, response=self)
>     HTTPError: 400 Client Error: Bad Request
>   stderr_lines: <omitted>
>   stdout: ''
>   stdout_lines: <omitted>

What you expected to happen:
Install and update grafana dashboards without errors

How to reproduce it (minimal and precise):

Share your group_vars files, inventory

**group_vars/all.yml**

> ---
> dummy:
> cluster: ceph-ovirt
> mon_group_name: mons
> osd_group_name: osds
> client_group_name: clients
> iscsi_gw_group_name: iscsigws
> mgr_group_name: mgrs
> configure_firewall: False
> ntp_service_enabled: false
> cephx: true
> monitor_interface: eno1
> ip_version: ipv4
> journal_size: 10240 # OSD journal size in MB
> public_network: 192.168.0.0/24
> cluster_network: 10.0.0.0/24
> osd_objectstore: bluestore
> os_tuning_params:
>   - { name: fs.file-max, value: 26234859 }
>   - { name: vm.zone_reclaim_mode, value: 0 }
>   - { name: vm.swappiness, value: 10 }
>   - { name: vm.min_free_kbytes, value: "{{ vm_min_free_kbytes }}" }
> containerized_deployment: True
> docker_pull_retry: 5
> docker_pull_timeout: "3600s"

**group_vars/osds.yml**

> ---
> dummy:
> api_user: admin
> api_password: admin
> api_port: 5000
> api_secure: false
> loop_delay: 1
> trusted_ip_list: 192.168.0.101,192.168.0.102,192.168.0.103

**group_vars/iscsigws.yml**

> ---
> dummy:
> devices:
>   - /dev/sda
>   - /dev/sdb
>   - /dev/sdc
>   - /dev/sdd
>   - /dev/sdf
>   - /dev/sdg
>   - /dev/sdh
> 

**/etc/ansible/hosts**

> [mons]
> node[1:3].internet.nio2
> [osds]
> node[1:3].internet.nio2
> [mgrs]
> node[1:3].internet.nio2
> [iscsigws]
> node1.internet.nio2
> node3.internet.nio2
> [grafana-server]
> nodeadmin.internet.nio2

**Environment**:
* OS (e.g. from /etc/os-release): 
> NAME="CentOS Linux"
> VERSION="7 (Core)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="7"
> PRETTY_NAME="CentOS Linux 7 (Core)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:7"
> HOME_URL="https://www.centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-7"
> CENTOS_MANTISBT_PROJECT_VERSION="7"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="7"

> CentOS Linux release 7.6.1810 (Core)

* Kernel (e.g. `uname -a`): 

> Linux nodeadmin.internet.nio2 5.1.5-1.el7.elrepo.x86_64 #1 SMP Sat May 25 16:10:51 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`): 

> Client:
>  Version:         1.13.1
>  API version:     1.26
>  Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
>  Go version:      go1.10.3
>  Git commit:      7f2769b/1.13.1
>  Built:           Sun Sep 15 14:06:47 2019
>  OS/Arch:         linux/amd64
> 
> Server:
>  Version:         1.13.1
>  API version:     1.26 (minimum version 1.12)
>  Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
>  Go version:      go1.10.3
>  Git commit:      7f2769b/1.13.1
>  Built:           Sun Sep 15 14:06:47 2019
>  OS/Arch:         linux/amd64
>  Experimental:    false

* Ansible version (e.g. `ansible-playbook --version`): 
> ansible-playbook 2.8.1
>   config file = /root/ceph-ansible-4.0/ansible.cfg
>   configured module search path = [u'/root/ceph-ansible-4.0/library']
>   ansible python module location = /usr/lib/python2.7/site-packages/ansible
>   executable location = /usr/bin/ansible-playbook
>   python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): 14.2.4

**Comment by Snegohod** [comment]
Same error after git pull to last version with commit https://github.com/ceph/ceph-ansible/commit/eb51cc1bb12b1059425c93e079d69c393df4be5c

> TASK [ceph-dashboard : inject grafana dashboard layouts] ************************************************************************
> Wednesday 09 October 2019  12:26:05 +0300 (0:00:00.167)       1:00:48.275 *****
> fatal: [node1.internet.nio2 -> node1.internet.nio2]: FAILED! => changed=false
>   cmd:
>   - docker
>   - exec
>   - ceph-mon-node1
>   - ceph
>   - --cluster
>   - ceph-ovirt
>   - dashboard
>   - grafana
>   - dashboards
>   - update
>   delta: '0:00:00.989808'
>   end: '2019-10-09 12:29:52.227641'
>   msg: non-zero return code
>   rc: 22
>   start: '2019-10-09 12:29:51.237833'
>   stderr: |-
>     Error EINVAL: Traceback (most recent call last):
>       File "/usr/share/ceph/mgr/mgr_module.py", line 914, in _handle_command
>         return self.handle_command(inbuf, cmd)
>       File "/usr/share/ceph/mgr/dashboard/module.py", line 450, in handle_command
>         push_local_dashboards()
>       File "/usr/share/ceph/mgr/dashboard/grafana.py", line 132, in push_local_dashboards
>         retry()
>       File "/usr/share/ceph/mgr/dashboard/grafana.py", line 89, in __call__
>         result = self.func(*self.args, **self.kwargs)
>       File "/usr/share/ceph/mgr/dashboard/grafana.py", line 127, in push
>         grafana.push_dashboard(body)
>       File "/usr/share/ceph/mgr/dashboard/grafana.py", line 54, in push_dashboard
>         response.raise_for_status()
>       File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
>         raise HTTPError(http_error_msg, response=self)
>     HTTPError: 400 Client Error: Bad Request
>   stderr_lines: <omitted>
>   stdout: ''
>   stdout_lines: <omitted>
