### ISSUE TITLE
Incorrect disk size quoting leads to `invalid literal for float()`

### ISSUE THREAD

**Issue by EBCEEB** [ceph/ceph-ansible#4577]
Got trace while trying to deploy Ceph Nautilus (community 14.2.4) using stable-4.0 branch:

```fatal: [<my-cool-server-name>]: FAILED! => changed=false 
  cmd:
  - ceph-volume
  - --cluster
  - ceph
  - lvm
  - batch
  - --bluestore
  - --yes
  - /dev/sda1
  - --report
  - --format=json
  msg: non-zero return code
  rc: 1
  stderr: |-
    Traceback (most recent call last):
      File "/usr/sbin/ceph-volume", line 9, in <module>
        load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
      File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
        self.main(self.argv)
      File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
        return f(*a, **kw)
      File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
        terminal.dispatch(self.mapper, subcommand_args)
      File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
        terminal.dispatch(self.mapper, self.argv)
      File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
        return func(*a, **kw)
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 320, in main
        self._get_strategy()
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 303, in _get_strategy
        self.strategy = strategy.with_auto_devices(self.args, unused_devices)
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 25, in with_auto_devices
        return cls(args, devices)
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 20, in __init__
        self.validate_compute()
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/strategies.py", line 30, in validate_compute
        self.validate()
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 61, in validate
        self.data_devs, osds_per_device=self.osds_per_device
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/validators.py", line 12, in minimum_device_size
        device_size = disk.Size(b=device.lvm_size.b)
      File "/usr/lib/python2.7/site-packages/ceph_volume/util/device.py", line 300, in lvm_size
        lvm_size = disk.Size(gb=size.gb.as_int()) - disk.Size(gb=1)
      File "/usr/lib/python2.7/site-packages/ceph_volume/util/disk.py", line 672, in __getattr__
        return formatter(float(self._b) / factor)
    ValueError: invalid literal for float(): 1.08 TB
```
Looks like `1.08 TB` is parsed as float.

**Comment by dsavineau** [comment]
If it's an issue with ceph-volume then you should open an issue on the Ceph tracker [1]

Also why are you using /dev/sda1 ? it should be the raw devices instead like /dev/sda

[1] https://tracker.ceph.com/projects/ceph-volume

**Comment by EBCEEB** [comment]
> Also why are you using /dev/sda1 ? it should be the raw devices instead like /dev/sda

It is a test environment having one disk.
