### ISSUE TITLE
ansible-playbook fails

### ISSUE THREAD

**Issue by gfz-marco** [ceph/ceph-ansible#4735]
**executing "ansible-playbook site.yml" fails, with python error**

```console
fatal: [dms12]: FAILED! => changed=false
  cmd:
  - ceph-volume
  - --cluster
  - ceph
  - lvm
  - batch
  - --bluestore
  - --yes
  - /dev/mapper/OSD_1
  - /dev/mapper/OSD_2
  - /dev/mapper/OSD_3
  - /dev/dm-2
  - /dev/dm-1
  - /dev/dm-0
  - --report
  - --format=json
  msg: non-zero return code
  rc: 1
  stderr: |-
    Traceback (most recent call last):
      File "/sbin/ceph-volume", line 9, in <module>
        load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
      File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
        self.main(self.argv)
      File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
        return f(*a, **kw)
      File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
        terminal.dispatch(self.mapper, subcommand_args)
      File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
        terminal.dispatch(self.mapper, self.argv)
      File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
        return func(*a, **kw)
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 320, in main
        self._get_strategy()
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 303, in _get_strategy
        self.strategy = strategy.with_auto_devices(self.args, unused_devices)
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 25, in with_auto_devices
        return cls(args, devices)
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 20, in __init__
        self.validate_compute()
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/strategies.py", line 30, in validate_compute
        self.validate()
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 61, in validate
        self.data_devs, osds_per_device=self.osds_per_device
      File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/validators.py", line 12, in minimum_device_size
        device_size = disk.Size(b=device.lvm_size.b)
      File "/usr/lib/python2.7/site-packages/ceph_volume/util/device.py", line 299, in lvm_size
        size = disk.Size(b=self.size)
      File "/usr/lib/python2.7/site-packages/ceph_volume/util/device.py", line 291, in size
        return self.sys_api['size']
    KeyError: 'size'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Comment by dsavineau** [comment]
the ceph-volume lvm batch command only supports raw devices (ie: /dev/sdb, /dev/nvme0n1, etc...) not logical volume

**Comment by gfz-marco** [comment]
Thanks, didn't realize that...
