### ISSUE TITLE
Fail in file "roles/ceph-mon/tasks/ceph_keys.yml"

### ISSUE THREAD

**Issue by databill** [ceph/ceph-ansible#479]
Ansible Host: Ubuntu 14.04 or OSX 10.11.01
Target: 3 bare metal nodes(Ubuntu 14.04) not VM
git clone the newest code

The deployment fail on the bellow yml part:
`shell: ls -1 /etc/ceph/*.keyring` it returns no result.

```
- name: find ceph keys                                                                               
  shell: ls -1 /etc/ceph/*.keyring
  changed_when: false
  register: ceph_keys
  when: cephx

- name: set keys permissions
  sudo: yes
  file:
    path: "{{ item }}"
    mode: 0600
    owner: root
    group: root
  with_items:
    - "{{ ceph_keys.stdout_lines }}"
```

#### It works **fine** without filter `*.keyring`
```
julien@julien-htpc:~$ ansible sds -m command -a "sudo ls -1 /etc/ceph/"
sds-03 | success | rc=0 >>
ceph.client.admin.keyring
ceph.conf
rbdmap

sds-01 | success | rc=0 >>
ceph.client.admin.keyring
ceph.conf
rbdmap

sds-02 | success | rc=0 >>
ceph.client.admin.keyring
ceph.conf
rbdmap
```
#### It **failed** when with `*.keyring` filter 
```
julien@julien-htpc:~$ ansible -vvv sds -m command -a "sudo ls -1 /etc/ceph/*.keyring"
<sds-02> ESTABLISH CONNECTION FOR USER: julien
<sds-01> ESTABLISH CONNECTION FOR USER: julien
<sds-03> ESTABLISH CONNECTION FOR USER: julien
<sds-02> REMOTE_MODULE command sudo ls -1 /etc/ceph/*.keyring
<sds-01> REMOTE_MODULE command sudo ls -1 /etc/ceph/*.keyring
<sds-03> REMOTE_MODULE command sudo ls -1 /etc/ceph/*.keyring
<sds-02> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/julien/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 sds-02 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452684892.66-233342426689884 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1452684892.66-233342426689884 && echo $HOME/.ansible/tmp/ansible-tmp-1452684892.66-233342426689884'
<sds-03> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/julien/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 sds-03 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452684892.66-35747957141811 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1452684892.66-35747957141811 && echo $HOME/.ansible/tmp/ansible-tmp-1452684892.66-35747957141811'
<sds-01> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/julien/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 sds-01 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452684892.67-134658508891165 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1452684892.67-134658508891165 && echo $HOME/.ansible/tmp/ansible-tmp-1452684892.67-134658508891165'
<sds-03> PUT /tmp/tmpG72f6x TO /home/julien/.ansible/tmp/ansible-tmp-1452684892.66-35747957141811/command
<sds-01> PUT /tmp/tmp5d_KiX TO /home/julien/.ansible/tmp/ansible-tmp-1452684892.67-134658508891165/command
<sds-02> PUT /tmp/tmppeAbmz TO /home/julien/.ansible/tmp/ansible-tmp-1452684892.66-233342426689884/command
<sds-03> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/julien/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 sds-03 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /home/julien/.ansible/tmp/ansible-tmp-1452684892.66-35747957141811/command; rm -rf /home/julien/.ansible/tmp/ansible-tmp-1452684892.66-35747957141811/ >/dev/null 2>&1'
<sds-01> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/julien/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 sds-01 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /home/julien/.ansible/tmp/ansible-tmp-1452684892.67-134658508891165/command; rm -rf /home/julien/.ansible/tmp/ansible-tmp-1452684892.67-134658508891165/ >/dev/null 2>&1'
<sds-02> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/julien/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 sds-02 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /home/julien/.ansible/tmp/ansible-tmp-1452684892.66-233342426689884/command; rm -rf /home/julien/.ansible/tmp/ansible-tmp-1452684892.66-233342426689884/ >/dev/null 2>&1'
sds-03 | FAILED | rc=2 >>
ls: cannot access /etc/ceph/*.keyring: No such file or directory

sds-02 | FAILED | rc=2 >>
ls: cannot access /etc/ceph/*.keyring: No such file or directory

sds-01 | FAILED | rc=2 >>
ls: cannot access /etc/ceph/*.keyring: No such file or directory
```
It seems that it cause python failure:
```
>>> subprocess.Popen('sudo ls /etc/ceph/*.keyring')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by leseb** [comment]
You used the `command` module, use `shell` instead.

**Comment by leseb** [comment]
Closing this, feel free to reopen.

**Comment by databill** [comment]
Hi [leseb](https://github.com/leseb)
Thanks for your guiding.
You are right to use shell in the test script, but it actually **failed in the playbook** when I perform the whole script and the result I have pasted above!
The test script is just used to trouble shooting.

**Comment by leseb** [comment]
@databill can you share the error of the play?
thanks!

**Comment by leseb** [comment]
Please reopen with the playbook error :).
