### ISSUE TITLE
Dashboard custom login breaks deployment in containerized setup

### ISSUE THREAD

**Issue by dmitry-rachkov** [ceph/ceph-ansible#5491]
**Bug Report**

During deployment of cluster (bare-metal, containerized) the change of default admin login for dashboard breaks deployment with following error: 

ceph-dashboard : inject grafana dashboard layouts
```
fatal: node1 -> 192.168.1.4]: FAILED! => changed=false 
  cmd:
  - podman
  - exec
  - ceph-mon-osce1
  - ceph
  - --cluster
  - ceph
  - dashboard
  - grafana
  - dashboards
  - update
  delta: '0:00:00.600263'
  end: '2020-07-02 13:43:40.397778'
  msg: non-zero return code
  rc: 22
  start: '2020-07-02 13:43:39.797515'
  stderr: |-
    Error EINVAL: Traceback (most recent call last):
      File "/usr/share/ceph/mgr/mgr_module.py", line 1153, in _handle_command
        return self.handle_command(inbuf, cmd)
      File "/usr/share/ceph/mgr/dashboard/module.py", line 392, in handle_command
        push_local_dashboards()
      File "/usr/share/ceph/mgr/dashboard/grafana.py", line 136, in push_local_dashboards
        retry()
      File "/usr/share/ceph/mgr/dashboard/grafana.py", line 93, in __call__
        result = self.func(*self.args, **self.kwargs)
      File "/usr/share/ceph/mgr/dashboard/grafana.py", line 131, in push
        grafana.push_dashboard(body)
      File "/usr/share/ceph/mgr/dashboard/grafana.py", line 58, in push_dashboard
        response.raise_for_status()
      File "/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://ceph-dashboard.sh.net:3000/api/dashboards/db
  
    Error: non zero exit code: 22: OCI runtime error
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**What happened:**
Deployment of new cluster fails after on dashboard playbook, task  `ceph-dashboard : inject grafana dashboard layouts` whenever group_vars are modified with custom login for dashboard

**What you expected to happen:**
A successful cluster deployment with dashboard having a custom login name based on group_vars all.yml

**How to reproduce it (minimal and precise):**
- Bare-metal installation, 4 nodes total, 1 used for [grafana-server]
- Deploy new cluster ->  with custom login in vars:
example
```
dashboard_admin_user: ceph
```

Share your group_vars files, inventory and **full** ceph-ansibe log

**Inventory**
node1 ansible_host=192.168.1.4 monitor_address=192.168.1.4
node2 ansible_host=192.168.1.5 monitor_address=192.168.1.5
node3 ansible_host=192.168.1.6 monitor_address=192.168.1.6
node4 ansible_host=192.168.1.7

[mons]
node1
node2
node3

[mgrs]
node1
node2
node3

[osds]
node1
node2
node3
node4

[mdss]
node1
node2
node3
node4

[grafana-server]
node4

**Environment**:
* OS (e.g. from /etc/os-release):
Ansible-controller
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
OSD, MGR. MON, MDS nodes

```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
```
* Kernel (e.g. `uname -a`):

```
[root@node1 ~]# uname -a
Linux osce1.sh.net 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
* Docker version if applicable (e.g. `docker version`):

```
[root@node1 ~]# podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64
```

* Ansible version (e.g. `ansible-playbook --version`):

```
ansible-playbook 2.9.9
  config file = /tmp/20200701T134544/ceph-ansible/ansible.cfg
  configured module search path = ['/tmp/20200701T134544/ceph-ansible/library']
  ansible python module location = /data/python/virtenvs/ceph-ansible/lib/python3.6/site-packages/ansible
  executable location = /data/python/virtenvs/ceph-ansible/bin/ansible-playbook
  python version = 3.6.9 (default, Nov 11 2019, 11:24:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

* ceph-ansible version (e.g. `git head or tag or stable branch`):

```
(ceph-ansible) (python3) [user@kvm1 ceph-ansible]$ git b
  master
* stable-5.0
```
* Ceph version (e.g. `ceph -v`):
octopus

* Ceph config group_vars
```
(ceph-ansible) (python3) [user@kvm1 ceph-ansible]$ find group_vars/ -type f | xargs grep -v -E "^#|^$" | cut -d: -f2,3,4,5
---
dummy:
configure_firewall: False
ntp_service_enabled: true
ntp_daemon_type: chronyd
ceph_origin: repository
ceph_repository: community
ceph_stable_release: octopus
monitor_interface: eno1
ip_version: ipv4
public_network: 192.168.1.1/24
ceph_docker_image: "ceph/daemon"
ceph_docker_image_tag: latest
ceph_docker_registry: docker.io
containerized_deployment: True
node_exporter_container_image: "docker.io/prom/node-exporter:v0.17.0"
grafana_server_fqdn: 'ceph-dashboard.sh.net'
grafana_container_image: "docker.io/grafana/grafana:5.4.3"
grafana_datasource: Dashboard
grafana_dashboards_path: "/etc/grafana/dashboards/ceph-dashboard"
grafana_dashboard_version: master
grafana_plugins:                                                                                                                                                             
  - vonage-status-panel
  - grafana-piechart-panel
prometheus_container_image: "docker.io/prom/prometheus:v2.7.2"
alertmanager_container_image: "docker.io/prom/alertmanager:v0.16.2"
dashboard_admin_user: ceph
dashboard_admin_password: "ceph@isCool"
grafana_admin_user: ceph
grafana_admin_password: "CephItup"
---
dummy:
monitor_secret: "{{ monitor_keyring.stdout }}"
secure_cluster: false
admin_secret: '<my_custom_key>'
---
dummy:
ceph_mgr_packages:
  - ceph-mgr
mgr_secret: '<my_custom_key>'
---
dummy:
devices:
  - /dev/nvme0n1
---
dummy:
---
dummy:
---
dummy:
---
```

Thanks

**Comment by dsavineau** [comment]
That's because updating the grafana user/password isn't supported by ceph-ansible at the moment.

**Comment by dmitry-rachkov** [comment]
I seem thanks. Can I suggest then put a clear comment in all.yml or even better remove the variable from the group_vars (there could be just a comment, default login is admin).

**Comment by jeevadotnet** [comment]
What is the update to this? Getting the same issue with ceph-ansible stable-6.0 

grafana_admin_user: admin
grafana_admin_password: admin

**Comment by Codeerror** [comment]
Delete all file in grafana-server
- /etc/grafana/dashboards
- /etc/grafana/grafana.ini
- /etc/grafana/provisioning
- /var/lib/grafana
- /etc/alertmanager
- /var/lib/alertmanager
- /var/lib/prometheus
- /etc/prometheus
