### ISSUE TITLE
No module named 'radosgw' with Playbook rgw-add-users-buckets.yml 

### ISSUE THREAD

**Issue by ltsavar** [ceph/ceph-ansible#5981]
**Bug Report**

What happened: trying to use infrastructure-playbooks/rgw-add-users-buckets.yml 

```console
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'radosgw'
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ceph_add_users_buckets_payload_x4hfs2oh/ansible_ceph_add_users_buckets_payload.zip/ansible/modules/ceph_add_users_buckets.py", line 11, in <module>
    ModuleNotFoundError: No module named 'radosgw'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

What you expected to happen:
the playbook should run.
I don't know any python modul radosgw. The module rados is installed. I tried it on a machine with python 2.7 and one with python 3.8. Same error. What am i missing?

How to reproduce it (minimal and precise):
1. Check out ceph-ansible
2. run playbook: ansible-playbook infrastructure-playbooks/rgw-add-users-buckets.yml 
3. see error

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu
* Kernel (e.g. `uname -a`): 5.8.0
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): 2.9.9
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable 5.0
* Ceph version (e.g. `ceph -v`): 15.2.5

**Comment by dsavineau** [comment]
This playbook relies on the ceph_add_users_buckets ansible module which depends on the radosgw python module [1].

You need to install the radosgw-admin package [2] on your ansible controller

[1] https://github.com/ceph/ceph-ansible/blob/master/library/ceph_add_users_buckets.py#L11
[2] https://pypi.org/project/radosgw-admin/
