### ISSUE TITLE
use ceph-volume lvm batch to create bluestore osds failed

### ISSUE THREAD

**Issue by quangln94** [ceph/ceph-ansible#6160]
i have problem when create OSD Bluestore in ceph 15.2.8:
```sh
fatal: [cephssd04-ntl2]: FAILED! => changed=true
  cmd:
  - ceph-volume
  - --cluster
  - ceph
  - lvm
  - batch
  - --bluestore
  - --yes
  - --crush-device-class
  - ssd
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/sdh
  - /dev/sdi
  - /dev/sdj
  - /dev/sdk
  - /dev/sdl
  - /dev/sdm
  - /dev/sdn
  - /dev/sdo
  - /dev/sdp
  - /dev/sdq
  delta: '0:00:05.961232'
  end: '2020-12-22 08:54:34.677609'
  msg: non-zero return code
  rc: 1
  start: '2020-12-22 08:54:28.716377'
  stderr: |-
    --> DEPRECATION NOTICE
    --> You are using the legacy automatic disk sorting behavior
    --> The Pacific release will change the default to --no-auto
    --> passed data devices: 16 physical, 0 LVM
    --> relative data size: 1.0
    Running command: /bin/ceph-authtool --gen-print-key
    Running command: /bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 9f766493-ccac-4e25-94ef-e94e7f733d92
    Running command: /sbin/vgcreate --force --yes ceph-019dba9e-df79-4497-b348-3ef67b65e5fe /dev/sdb
     stdout: Physical volume "/dev/sdb" successfully created.
     stdout: Volume group "ceph-019dba9e-df79-4497-b348-3ef67b65e5fe" successfully created
    Running command: /sbin/lvcreate --yes -l 457855 -n osd-block-9f766493-ccac-4e25-94ef-e94e7f733d92 ceph-019dba9e-df79-4497-b348-3ef67b65e5fe
     stderr: Volume group "ceph-019dba9e-df79-4497-b348-3ef67b65e5fe" has insufficient free space (457854 extents): 457855 required.
    --> Was unable to complete a new OSD, will rollback changes
    Running command: /bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.88 --yes-i-really-mean-it
     stderr: 2020-12-22T08:54:34.455+0700 7f3162ace700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.bootstrap-osd.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
    2020-12-22T08:54:34.455+0700 7f3162ace700 -1 AuthRegistry(0x7f315c0593c0) no keyring found at /etc/ceph/ceph.client.bootstrap-osd.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx
     stderr: purged osd.88
    Traceback (most recent call last):
      File "/sbin/ceph-volume", line 11, in <module>
        load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
      File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
        self.main(self.argv)
      File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
        return f(*a, **kw)
      File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
        terminal.dispatch(self.mapper, subcommand_args)
      File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
        terminal.dispatch(self.mapper, self.argv)
      File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
        return func(*a, **kw)
      File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 415, in main
        self._execute(plan)
      File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 434, in _execute
        c.create(argparse.Namespace(**args))
      File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
        return func(*a, **kw)
      File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/create.py", line 26, in create
        prepare_step.safe_prepare(args)
      File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/prepare.py", line 252, in safe_prepare
        self.prepare()
      File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
        return func(*a, **kw)
      File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/prepare.py", line 363, in prepare
        block_lv = self.prepare_data_device('block', osd_fsid)
      File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/prepare.py", line 221, in prepare_data_device
        **kwargs)
      File "/usr/lib/python3.6/site-packages/ceph_volume/api/lvm.py", line 949, in create_lv
        process.run(command)
      File "/usr/lib/python3.6/site-packages/ceph_volume/process.py", line 153, in run
        raise RuntimeError(msg)
    RuntimeError: command returned non-zero exit status: 5
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
How can i fix it ?

Thanks!

**Comment by dsavineau** [comment]
I think you should report this on the ceph-volume tracker as it isn't related to ceph-ansible.

https://tracker.ceph.com/projects/ceph-volume

Note that this looks very similar to

https://tracker.ceph.com/issues/47758
https://tracker.ceph.com/issues/48383
