### ISSUE TITLE
OSD role does not support using a partition as Bluestore block-db device

### ISSUE THREAD

**Issue by dvusboy** [ceph/ceph-ansible#6249]
**Bug Report**

What happened:

I'm trying to create an OSD on a server with the following disk layout:

```
NAME                          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                             8:0    0 223.6G  0 disk
├─sda1                          8:1    0     1M  0 part
├─sda2                          8:2    0     2G  0 part /boot
├─sda3                          8:3    0    10G  0 part
└─sda4                          8:4    0 211.6G  0 part
  ├─vg_system-lv_root         253:0    0    64G  0 lvm  /
  ├─vg_system-lv_swap         253:1    0     2G  0 lvm  [SWAP]
  ├─vg_system-lv_docker_tmeta 253:2    0     2G  0 lvm
  │ └─vg_system-lv_docker     253:4    0   100G  0 lvm
  └─vg_system-lv_docker_tdata 253:3    0   100G  0 lvm
    └─vg_system-lv_docker     253:4    0   100G  0 lvm
sdb                             8:16   0   1.8T  0 disk
```

* `sda3` will be used for the Bluestore DB
* `sdb` will be the main data device

I have these `group_vars` values set for `osds.yml`:

```
devices:
  - /dev/sdb
dedicated_devices:
  - /dev/sda3
```

I got the following error from `roles/ceph-osd/tasks/scenarios/lvm-batch.yml`:

```
fatal: [r03u05-d.hq.verseon.us]: FAILED! => {"changed": true, "cmd": ["ceph-volume", "--cluster", "ceph", "lvm", "batch", "--bluestore", "--yes", "/dev/sdb", "--db-devices", "/dev/sda3", "--report", "--format=json"], "msg": "non-zero return code", "rc": 1, "stderr": "--> passed data devices: 1 physical, 0 LVM\n--> relative data size: 1.0\n--> passed block_db devices: 0 physical, 1 LVM\nTraceback (most recent call last):\n  File \"/usr/sbin/ceph-volume\", line 9, in <module>\n    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/main.py\", line 39, in __init__\n    self.main(self.argv)\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/decorators.py\", line 59, in newfunc\n    return f(*a, **kw)\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/main.py\", line 150, in main\n    terminal.dispatch(self.mapper, subcommand_args)\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/terminal.py\", line 194, in dispatch\n    instance.main()\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py\", line 42, in main\n    terminal.dispatch(self.mapper, self.argv)\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/terminal.py\", line 194, in dispatch\n    instance.main()\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/decorators.py\", line 16, in is_root\n    return func(*a, **kw)\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 402, in main\n    plan = self.get_plan(self.args)\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 440, in get_plan\n    args.wal_devices)\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 472, in get_deployment_layout\n    fast_type)\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 509, in fast_allocations\n    ret.extend(get_lvm_fast_allocs(lvm_devs))\n  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 147, in get_lvm_fast_allocs\n    d.used_by_ceph]\nIndexError: list index out of range", "stderr_lines": ["--> passed data devices: 1 physical, 0 LVM", "--> relative data size: 1.0", "--> passed block_db devices: 0 physical, 1 LVM", "Traceback (most recent call last):", "  File \"/usr/sbin/ceph-volume\", line 9, in <module>", "    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/main.py\", line 39, in __init__", "    self.main(self.argv)", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/decorators.py\", line 59, in newfunc", "    return f(*a, **kw)", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/main.py\", line 150, in main", "    terminal.dispatch(self.mapper, subcommand_args)", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/terminal.py\", line 194, in dispatch", "    instance.main()", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py\", line 42, in main", "    terminal.dispatch(self.mapper, self.argv)", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/terminal.py\", line 194, in dispatch", "    instance.main()", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/decorators.py\", line 16, in is_root", "    return func(*a, **kw)", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 402, in main", "    plan = self.get_plan(self.args)", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 440, in get_plan", "    args.wal_devices)", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 472, in get_deployment_layout", "    fast_type)", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 509, in fast_allocations", "    ret.extend(get_lvm_fast_allocs(lvm_devs))", "  File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 147, in get_lvm_fast_allocs", "    d.used_by_ceph]", "IndexError: list index out of range"], "stdout": "", "stdout_lines": []}
```

I ran the command `ceph-volume --log-level DEBUG --log-path /root/ceph-volume.log --cluster ceph lvm batch --bluestore --yes /dev/sdb --db-devices /dev/sda3 --report` on the server and got this:

Output:

```
--> passed data devices: 1 physical, 0 LVM
--> relative data size: 1.0
--> passed block_db devices: 0 physical, 1 LVM
-->  IndexError: list index out of range
```

Backtrace in the log:

```
[2021-02-05 18:10:04,340][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 150, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 402, in main
    plan = self.get_plan(self.args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 440, in get_plan
    args.wal_devices)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 472, in get_deployment_layout
    fast_type)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 509, in fast_allocations
    ret.extend(get_lvm_fast_allocs(lvm_devs))
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 147, in get_lvm_fast_allocs
    d.used_by_ceph]
IndexError: list index out of range
```

What you expected to happen:

I expect this step to succeed. This has worked before, when I first rolled out Ceph Nautilus on my cluster of machines. All of the OSD nodes have exactly the same setup. Here is an example:

```
NAME                                                                                                                    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                                                                                                                       8:0    0 223.6G  0 disk
├─sda1                                                                                                                    8:1    0     1M  0 part
├─sda2                                                                                                                    8:2    0     2G  0 part /boot
├─sda3                                                                                                                    8:3    0    10G  0 part
│ └─ceph--block--dbs--437473dd--0a41--4df7--aec3--4e297b09705d-osd--block--db--5f22db5f--ab00--4d90--865d--c5405dc59fe1 253:6    0    10G  0 lvm
└─sda4                                                                                                                    8:4    0 211.6G  0 part
  ├─vg_system-lv_root                                                                                                   253:1    0    64G  0 lvm  /
  ├─vg_system-lv_swap                                                                                                   253:2    0     2G  0 lvm
  ├─vg_system-lv_docker_tmeta                                                                                           253:3    0     2G  0 lvm
  │ └─vg_system-lv_docker                                                                                               253:5    0   100G  0 lvm
  └─vg_system-lv_docker_tdata                                                                                           253:4    0   100G  0 lvm
    └─vg_system-lv_docker                                                                                               253:5    0   100G  0 lvm
sdb                                                                                                                       8:16   0   3.7T  0 disk
└─ceph--block--4139cdb8--aeea--4949--bbaa--a0080cc49e31-osd--block--0b544667--5950--40ac--828d--391d1861aec8            253:0    0   3.7T  0 lvm
```

How to reproduce it (minimal and precise):

I track down the problem to `ceph-volume` treating **a partition** as **a logical volume** in [batch.py:45](https://github.com/ceph/ceph/blob/nautilus/src/ceph-volume/ceph_volume/devices/lvm/batch.py#L45). Replacing `d.is_device` with `d.is_acceptable_device` appears to fix the problem. I don't know when this happened upstream.

**Environment**:
* OS (e.g. from /etc/os-release): `CentOS 7`
* Kernel (e.g. `uname -a`): `3.10.0-1160.15.2.el7.x86_64`
* Docker version if applicable (e.g. `docker version`): N/A
* Ansible version (e.g. `ansible-playbook --version`): `2.9.13`
* ceph-ansible version (e.g. `git head or tag or stable branch`): `v4.0.32`
* Ceph version (e.g. `ceph -v`): `ceph version 14.2.16 (762032d6f509d5e7ee7dc008d80fe9c87086603c) nautilus (stable)` (with `ceph-base-14.2.16-1.el7.x86_64`).

**Comment by dsavineau** [comment]
That's probably something related to ceph-volume but as far as I remember `ceph-volume lvm batch` does not support using partitions, only raw devices.

If you want to use partitions for block.db or block.wal you have to use `lvm_volumes` rather than `devices`/`dedicated_devices`

```yaml
devices:
  - /dev/sdb
dedicated_devices:
  - /dev/sda3
```

to

```yaml
lvm_volumes:
  - data: /dev/sdb
    db: /dev/sda3
```
