### ISSUE TITLE
Deployment fails at deploying monitors

### ISSUE THREAD

**Issue by nicolamori** [ceph/ceph-ansible#7036]
**Bug Report**

I'm trying ceph-ansible with a pair of VMs to test it, and apologize in advance for any dumb mistake I may have made since I'm a beginner. The deployment stops with error at:
```
TASK [ceph-mon : ceph monitor mkfs with keyring] *****************************************************************************************************************************************************************************************************************************
task path: /home/mori/ceph-ansible/roles/ceph-mon/tasks/deploy_monitors.yml:126
martedì 04 gennaio 2022  17:21:22 +0100 (0:00:00.016)       0:03:19.439 ******* 
<90.147.174.73> ESTABLISH SSH CONNECTION FOR USER: None
<90.147.174.73> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=60 -o ControlPath=/home/mori/.ansible/cp/%h-%r-%p 90.147.174.73 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<90.147.174.73> (0, b'/home/mori\n', b'')
<90.147.174.73> ESTABLISH SSH CONNECTION FOR USER: None
<90.147.174.73> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=60 -o ControlPath=/home/mori/.ansible/cp/%h-%r-%p 90.147.174.73 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/mori/.ansible/tmp `"&& mkdir "` echo /home/mori/.ansible/tmp/ansible-tmp-1641313282.8354132-61379-91921146492479 `" && echo ansible-tmp-1641313282.8354132-61379-91921146492479="` echo /home/mori/.ansible/tmp/ansible-tmp-1641313282.8354132-61379-91921146492479 `" ) && sleep 0'"'"''
<90.147.174.73> (0, b'ansible-tmp-1641313282.8354132-61379-91921146492479=/home/mori/.ansible/tmp/ansible-tmp-1641313282.8354132-61379-91921146492479\n', b'')
Using module file /usr/lib/python3.10/site-packages/ansible/modules/command.py
<90.147.174.73> PUT /home/mori/.ansible/tmp/ansible-local-59453oeyvrgwn/tmp4lqxqxp1 TO /home/mori/.ansible/tmp/ansible-tmp-1641313282.8354132-61379-91921146492479/AnsiballZ_command.py
<90.147.174.73> SSH: EXEC sftp -b - -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=60 -o ControlPath=/home/mori/.ansible/cp/%h-%r-%p '[90.147.174.73]'
<90.147.174.73> (0, b'sftp> put /home/mori/.ansible/tmp/ansible-local-59453oeyvrgwn/tmp4lqxqxp1 /home/mori/.ansible/tmp/ansible-tmp-1641313282.8354132-61379-91921146492479/AnsiballZ_command.py\n', b'')
<90.147.174.73> ESTABLISH SSH CONNECTION FOR USER: None
<90.147.174.73> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=60 -o ControlPath=/home/mori/.ansible/cp/%h-%r-%p 90.147.174.73 '/bin/sh -c '"'"'chmod u+x /home/mori/.ansible/tmp/ansible-tmp-1641313282.8354132-61379-91921146492479/ /home/mori/.ansible/tmp/ansible-tmp-1641313282.8354132-61379-91921146492479/AnsiballZ_command.py && sleep 0'"'"''
<90.147.174.73> (0, b'', b'')
<90.147.174.73> ESTABLISH SSH CONNECTION FOR USER: None
<90.147.174.73> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=60 -o ControlPath=/home/mori/.ansible/cp/%h-%r-%p -tt 90.147.174.73 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-jbqivknkxfgqylyfgghljcljccpbkfwp ; /usr/bin/python /home/mori/.ansible/tmp/ansible-tmp-1641313282.8354132-61379-91921146492479/AnsiballZ_command.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<90.147.174.73> (1, b'\r\n{"changed": true, "end": "2022-01-04 16:21:23.640456", "stdout": "", "cmd": ["ceph-mon", "--cluster", "ceph", "--setuser", "ceph", "--setgroup", "ceph", "--mkfs", "-i", "vnode-0", "--fsid", "64a417a0-5437-4aff-bf28-9763dc2cc3bb", "--keyring", "/var/lib/ceph/tmp/ceph.mon..keyring"], "failed": true, "delta": "0:00:00.047346", "stderr": "", "rc": 1, "invocation": {"module_args": {"creates": "/var/lib/ceph/mon/ceph-vnode-0/keyring", "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "ceph-mon --cluster ceph --setuser \\"ceph\\" --setgroup \\"ceph\\" --mkfs -i vnode-0 --fsid 64a417a0-5437-4aff-bf28-9763dc2cc3bb --keyring /var/lib/ceph/tmp/ceph.mon..keyring\\n", "removes": null, "argv": null, "warn": false, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "start": "2022-01-04 16:21:23.593110", "msg": "non-zero return code"}\r\n', b'Shared connection to 90.147.174.73 closed.\r\n')
<90.147.174.73> Failed to connect to the host via ssh: Shared connection to 90.147.174.73 closed.
<90.147.174.73> ESTABLISH SSH CONNECTION FOR USER: None
<90.147.174.73> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=60 -o ControlPath=/home/mori/.ansible/cp/%h-%r-%p 90.147.174.73 '/bin/sh -c '"'"'rm -f -r /home/mori/.ansible/tmp/ansible-tmp-1641313282.8354132-61379-91921146492479/ > /dev/null 2>&1 && sleep 0'"'"''
<90.147.174.73> (0, b'', b'')
fatal: [90.147.174.73]: FAILED! => changed=true 
  cmd:
  - ceph-mon
  - --cluster
  - ceph
  - --setuser
  - ceph
  - --setgroup
  - ceph
  - --mkfs
  - -i
  - vnode-0
  - --fsid
  - 64a417a0-5437-4aff-bf28-9763dc2cc3bb
  - --keyring
  - /var/lib/ceph/tmp/ceph.mon..keyring
  delta: '0:00:00.047346'
  end: '2022-01-04 16:21:23.640456'
  invocation:
    module_args:
      _raw_params: |-
        ceph-mon --cluster ceph --setuser "ceph" --setgroup "ceph" --mkfs -i vnode-0 --fsid 64a417a0-5437-4aff-bf28-9763dc2cc3bb --keyring /var/lib/ceph/tmp/ceph.mon..keyring
      _uses_shell: false
      argv: null
      chdir: null
      creates: /var/lib/ceph/mon/ceph-vnode-0/keyring
      executable: null
      removes: null
      stdin: null
      stdin_add_newline: true
      strip_empty_ends: true
      warn: false
  msg: non-zero return code
  rc: 1
  start: '2022-01-04 16:21:23.593110'
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
Connecting to the VM and launching the command manually produces a return code 1 and no message on logs nor on console (even   with `-d`).

What you expected to happen:
The deployment should not fail.

How to reproduce it (minimal and precise):
I modified the `roles/ceph-validate/tasks/check_system.yml` to make the ansible version check succeed with ansible 2.12, then created the group_vars files and inventory as below and then launched `ansible-playbook -i invfile site.yml`

Share your group_vars files, inventory and **full** ceph-ansibe log
group_vars/all.yml :
```
---
dummy:
cluster: ceph
mon_group_name: mons
osd_group_name: osds
ceph_origin: repository
ceph_repository: community
fsid: V45yHR5y45gffc3w454ye
monitor_interface: eth0
public_network: 90.147.174.0/24 
cluster_network: 90.147.174.0/24
dashboard_enabled: False
```

group_vars/osds.yml :
```
---
dummy:
devices:
  - /dev/vdb
```

Inventory file:
```
[mons]
90.147.174.73

[osds]
90.147.174.165
```

[ceph-ansible full log](https://basket.fi.infn.it:443/f/49f53a1d55/?dl=1)

**Environment** of the mon machine where the error happens:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): 3.10.0-1160.49.1.el7.x86_64
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-5.0 branch
* Ceph version (e.g. `ceph -v`): ceph version 15.2.15 (2dfb18841cfecc2f7eb7eb2afd65986ca4d95985) octopus (stable)

** Environment ** on machine used to launch the deployment:
* OS (e.g. from /etc/os-release): ArchLinux
Ansible version (e.g. `ansible-playbook --version`): ansible-playbook [core 2.12.1]

**Comment by guits** [comment]
> How to reproduce it (minimal and precise): I modified the `roles/ceph-validate/tasks/check_system.yml` to make the ansible version check succeed with ansible 2.12, then created the group_vars files and inventory as below and then launched `ansible-playbook -i invfile site.yml`

You shouldn't do that. You must use what is required by the playbook.
That being said, I don't think this is the cause of your issue here.

what if you run :
`ceph-mon --cluster ceph --setuser "ceph" --setgroup "ceph" --mkfs -i vnode-0 --fsid 64a417a0-5437-4aff-bf28-9763dc2cc3bb --keyring /var/lib/ceph/tmp/ceph.mon..keyring`

manually on the node `90.147.174.73` ?

**Comment by nicolamori** [comment]
@guits Yes I understand that one should use the ansible version required by the ceph-ansible version in use. I hacked ceph-ansible to use 2.12 since that's what's currently available on my development machine, and I just wanted to give ceoh-ansible an initial try. Then 2.12 seemed to work fine up to the reported error, on which I agree with you that it does not seem to be related to the mismatched ansible version (otherwise I would not open this issue).

Anyway, as I wrote in my first post issuing the command manually from the node's shell fails as well:
```bash
[mori@vnode-0 ~]$ sudo ceph-mon --cluster ceph --setuser "ceph" --setgroup "ceph" --mkfs -i vnode-0 --fsid 64a417a0-5437-4aff-bf28-9763dc2cc3bb --keyring /var/lib/ceph/tmp/ceph.mon..keyring
[mori@vnode-0 ~]$ echo $?
1
[mori@vnode-0 ~]$ sudo ls /var/lib/ceph/tmp/ceph.mon..keyring
/var/lib/ceph/tmp/ceph.mon..keyring
[mori@vnode-0 ~]$ sudo cat /var/log/ceph/ceph-mon.vnode-0.log
[mori@vnode-0 ~]$
```
I get no console output even when using the `-c` option.

**Comment by guits** [comment]
is there a valid keyring in `/var/lib/ceph/tmp/ceph.mon..keyring` ?
have you tried to run that command with `--debug-ms xx` (where xx is the debug level) to increase the verbosity?

**Comment by guits** [comment]
@nicolamori any chance you can provide another ceph-ansible log with `-vv` ?
Thanks!

**Comment by nicolamori** [comment]
This is the content of the keyring file:
```
[mon.]
        key = AQAnd9RhAAAAABAASxjNT8Ji+sEmOCJS8PydNA==
        caps mon = "allow *"
```
Running with `--debug-ms 20` does not produce any console output nor log.

I'm purging the cluster and re-running `site.yml` with `-vv`, please hold on...

**Comment by guits** [comment]
what about the following..?
```
ceph-mon --debug_mon 20 --debug_ms 20 --cluster ceph --setuser "ceph" --setgroup "ceph" --mkfs -i vnode-0 --fsid 24888641-d1c2-42c6-b66c-5a3e4530af93 --keyring /var/lib/ceph/tmp/ceph.mon..keyring
```

**Comment by nicolamori** [comment]
```
[mori@vnode-0 ~]$ sudo ceph-mon --debug_mon 20 --debug_ms 20 --cluster ceph --setuser "ceph" --setgroup "ceph" --mkfs -i vnode-0 --fsid 24888641-d1c2-42c6-b66c-5a3e4530af93 --keyring /var/lib/ceph/tmp/ceph.mon..keyring
[mori@vnode-0 ~]$ echo $?
1
[mori@vnode-0 ~]$ sudo cat /var/log/ceph/ceph-mon.vnode-0.log
[mori@vnode-0 ~]$
```

**Comment by nicolamori** [comment]
It seems I found a way to get some console output:
```
[mori@vnode-0 ~]$ sudo su ceph -s /bin/bash -c "ceph-mon --debug_mon 20 --debug_ms 20 --cluster ceph --mkfs -i vnode-0 --fsid 24888641-d1c2-42c6-b66c-5a3e4530af93 --keyring /var/lib/ceph/tmp/ceph.mon..keyring"
2022-01-05T14:05:45.051+0000 7fc064793300 -1 unable to find any IP address in networks '90.147.174.0/24' interfaces ''
[mori@vnode-0 ~]$ echo $?
1
```
I then looked at the interfaces:
```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:9e:89:ee brd ff:ff:ff:ff:ff:ff
    inet 192.168.32.222/24 brd 192.168.32.255 scope global dynamic eth0
       valid_lft 65234sec preferred_lft 65234sec
    inet6 fe80::f816:3eff:fe9e:89ee/64 scope link 
       valid_lft forever preferred_lft forever
```
Actually, the network address I used in the configuration is the VM's public one, while from the VM console one can see just the internal network IP. I guess this might be the root cause of this issue, correct? Anyway I'm still puzzled about the lack of output when launching ceph-mon as root (either with sudo or directly as root).

**Comment by guits** [comment]
ah, true.
you might need to use `--err-to-stderr=true`  (to be double-checked though, I don't recall the exact param off the top of my head...)

**Comment by nicolamori** [comment]
Thank you @guits, using the correct IP the deployment does not give errors (actually it's currently stuck at `ceph-osd : use ceph-volume lvm batch to create bluestore osds`, but that's another story). Anyway, I have not been able to get the console output again, even using `sudo su ceph ...` as above. No idea why it behaves like this...

**Comment by guits** [comment]
@nicolamori do you have a ceph-ansible log for the ceph-volume task hanging? you might want to take a look at `/var/log/ceph/ceph-volume.log` too

**Comment by nicolamori** [comment]
The script gets stuck while polling for something. Launching the command from the node shell and the quitting with Ctrl-C I get this trace:
```
mori@vnode-0:~$ sudo /usr/bin/python3 /home/mori/.ansible/tmp/ansible-tmp-1641395958.135722-31817-133352975540240/AnsiballZ_ceph_volume.py
/tmp/ansible_ceph_volume_payload_l95r2d9c/ansible_ceph_volume_payload.zip
/tmp/ansible_ceph_volume_payload_l95r2d9c
b'{"ANSIBLE_MODULE_ARGS": {"cluster": "ceph", "objectstore": "bluestore", "batch_devices": ["/dev/vdb"], "dmcrypt": false, "crush_device_class": "", "osds_per_device": 1, "journal_size": 5120, "block_db_size": -1, "action": "batch", "_ansible_check_mode": false, "_ansible_no_log": false, "_ansible_debug": false, "_ansible_diff": false, "_ansible_verbosity": 3, "_ansible_version": "2.12.1", "_ansible_module_name": "ceph_volume", "_ansible_syslog_facility": "LOG_USER", "_ansible_selinux_special_fs": ["fuse", "nfs", "vboxsf", "ramfs", "9p", "vfat"], "_ansible_string_conversion_action": "warn", "_ansible_socket": null, "_ansible_shell_executable": "/bin/sh", "_ansible_keep_remote_files": false, "_ansible_tmpdir": "/home/mori/.ansible/tmp/ansible-tmp-1641395958.135722-31817-133352975540240/", "_ansible_remote_tmp": "~/.ansible/tmp"}}'
^CTraceback (most recent call last):
  File "/home/mori/.ansible/tmp/ansible-tmp-1641395958.135722-31817-133352975540240/AnsiballZ_ceph_volume.py", line 110, in <module>
    _ansiballz_main()
  File "/home/mori/.ansible/tmp/ansible-tmp-1641395958.135722-31817-133352975540240/AnsiballZ_ceph_volume.py", line 102, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/mori/.ansible/tmp/ansible-tmp-1641395958.135722-31817-133352975540240/AnsiballZ_ceph_volume.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.ceph_volume', init_globals=dict(_module_fqn='ansible.modules.ceph_volume', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ceph_volume_payload_l95r2d9c/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 798, in <module>
  File "/tmp/ansible_ceph_volume_payload_l95r2d9c/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 794, in main
  File "/tmp/ansible_ceph_volume_payload_l95r2d9c/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 764, in run_module
  File "/tmp/ansible_ceph_volume_payload_l95r2d9c/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 260, in exec_command
  File "/tmp/ansible_ceph_volume_payload_l95r2d9c/ansible_ceph_volume_payload.zip/ansible/module_utils/basic.py", line 2055, in run_command
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```
I found the [log file on the node](https://basket.fi.infn.it:443/f/fc340fe518/?dl=1); the only thing looking suspicious is:
```
[2022-01-05 16:03:00,400][ceph_volume.api.lvm][WARNING] device is not part of ceph: None
```
at the end of the file, but I can't tell for sure (sorry, noob here...). I think it's another stupid configuration error of mine, probably related to networking too.

**Comment by guits** [comment]
well, in order to debug this kind of failure, you can use the environment variable `ANSIBLE_KEEP_REMOTE_FILES=1` then go to the host that has executed the module so you can do some debug.

That would be a bit too long to explain here, if you are on IRC you can find me on OFTC (irc.oftc.net) nick: guits

**Comment by nicolamori** [comment]
Thank you very much for your kind availability, Guillaume. In the end I was right, the error was just due to closed ports on my VMs. After opening 6800-7300 as explained in the Ceph network configuration reference the deployment ended successfully. So my bad even in this case.
Thanks again for your great assistance!
