### ISSUE TITLE
add-mon.yml hangs 

### ISSUE THREAD

**Issue by badfiles** [ceph/ceph-ansible#7547]
**Bug Report**

What happened:

infrastructure-playbooks/add-mon.yml hangs on the monitor to be added

TASK [ceph-mon : Start the monitor service] ***********************************************************************************************************
ok: [hv4]
ok: [hv3]
changed: [hv5]
ok: [cephmgr]

...

TASK [ceph-mon : Fetch ceph initial keys] *************************************************************************************************************
ok: [hv3]
ok: [hv4]
ok: [cephmgr]
<4-th monitor should go here>

What you expected to happen:

add 4-th monitor to the cluster

**Environment**:
* OS (e.g. from /etc/os-release): AlmaLinux 9.3
* Kernel (e.g. `uname -a`): 5.14.0-362.24.1.el9_3.x86_64
* Docker version if applicable (e.g. `docker version`): ---
* Ansible version (e.g. `ansible-playbook --version`):  ansible [core 2.16.5] 
* ceph-ansible version (e.g. `git head or tag or stable branch`): master branch
* Ceph version (e.g. `ceph -v`): ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)

**Comment by badfiles** [comment]
same thing when trying to add osd's

TASK [ceph-osd : Create bootstrap-osd and osd directories] ********************************************************************************************
ok: [hv3] => (item=/var/lib/ceph/bootstrap-osd/)
ok: [hv4] => (item=/var/lib/ceph/bootstrap-osd/)
changed: [hv5] => (item=/var/lib/ceph/bootstrap-osd/)
ok: [hv3] => (item=/var/lib/ceph/osd/)
ok: [hv4] => (item=/var/lib/ceph/osd/)
changed: [hv5] => (item=/var/lib/ceph/osd/)

...

TASK [ceph-osd : Use ceph-volume lvm batch to create osds] ********************************************************************************************

this task hangs forever

on the host a bunch of python processes seem to do noting

i guess it's key distribution issue

![Screenshot from 2024-04-15 20-48-45](https://github.com/ceph/ceph-ansible/assets/1597304/2a7f4468-d174-4b1d-aaf4-a0fd9f4a9761)

**Comment by badfiles** [comment]
playbooks apply to existing members with no issue

**Comment by badfiles** [comment]
```
fatal: [hv5]: FAILED! => changed=true 
  cmd:
  - ceph-volume
  - --cluster
  - ceph
  - lvm
  - batch
  - --bluestore
  - --yes
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme3n1
  - /dev/nvme2n1
  delta: '0:14:18.745809'
  end: '2024-04-15 20:54:56.532008'
  msg: non-zero return code
  rc: 1
  start: '2024-04-15 20:40:37.786199'
  stderr: |-
    --> DEPRECATION NOTICE
    --> You are using the legacy automatic disk sorting behavior
    --> The Pacific release will change the default to --no-auto
    --> passed data devices: 4 physical, 0 LVM
    --> relative data size: 1.0
    Running command: /bin/ceph-authtool --gen-print-key
    Running command: /bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 1da4edee-9f19-452f-8b15-f48ebdca9bbc
    Traceback (most recent call last):
      File "/sbin/ceph-volume", line 33, in <module>
        sys.exit(load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')())
      File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 41, in __init__
        self.main(self.argv)
      File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 59, in newfunc
        return f(*a, **kw)
      File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 153, in main
        terminal.dispatch(self.mapper, subcommand_args)
      File "/usr/lib/python3.9/site-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/main.py", line 46, in main
        terminal.dispatch(self.mapper, self.argv)
      File "/usr/lib/python3.9/site-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 16, in is_root
        return func(*a, **kw)
      File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/batch.py", line 414, in main
        self._execute(plan)
      File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/batch.py", line 432, in _execute
        c.create(argparse.Namespace(**args))
      File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 16, in is_root
        return func(*a, **kw)
      File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/create.py", line 26, in create
        prepare_step.safe_prepare(args)
      File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/prepare.py", line 196, in safe_prepare
        self.prepare()
      File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 16, in is_root
        return func(*a, **kw)
      File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/prepare.py", line 236, in prepare
        self.osd_id = prepare_utils.create_id(osd_fsid, json.dumps(secrets), osd_id=self.args.osd_id)
      File "/usr/lib/python3.9/site-packages/ceph_volume/util/prepare.py", line 154, in create_id
        raise RuntimeError('Unable to create a new OSD id')
    RuntimeError: Unable to create a new OSD id
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
after terminating the parent process

**Comment by badfiles** [comment]
```
TASK [ceph-mon : Create monitor initial keyring] ******************************************************************************************************
changed: [hv4]
changed: [hv3]
changed: [cephmgr]

...


TASK [ceph-mon : Import admin keyring into mon keyring] ***********************************************************************************************
changed: [hv3]
changed: [hv4]
changed: [cephmgr]
```
every time I run site.yml this gets triggered
may it be part of the problem?

**Comment by badfiles** [comment]
the add-mon hangs on this command, it does nothing, just hangs, if I run it manually

TASK [ceph-mon : Fetch ceph initial keys] *************************************************************************************************************
ok: [hv3]
ok: [hv4]
ok: [cephmgr]


`[root@hv5 root]# /usr/bin/python3 -s /bin/ceph -n mon. -k /var/lib/ceph/mon/ceph-hv5/keyring --cluster ceph auth ls -f json
`

something is missing on the host, I cannot find out what
any /bin/ceph command hangs, no output, no debug output

but some commands give errors

[root@hv5 ceph-hv5]# /bin/ceph -n mon.
2024-04-17T09:34:51.166+0300 7fc65c8a1640 -1 auth: unable to find a keyring on /etc/ceph/ceph.mon..keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory

**Comment by badfiles** [comment]
```
Apr 17 09:51:17 hv5 ceph-mon[135244]: 2024-04-17T09:51:17.619+0300 7f8bc1a15b00 -1 no public_addr or public_network specified, and mon.hv5 not present in monmap or ceph.conf
```
I guess this is the reason why the service on new mon won't start and any ceph command hangs
this commit cuts out network params from ceph.conf

https://github.com/ceph/ceph-ansible/commit/14b4abf7c002c1db4c80f85116651bb33b9645e4

**Comment by badfiles** [comment]
it was a network issue, cluster network on the new host was configured to use MTU=9000, but network could not deliver such packages, other hosts were configured to use MTU=9000 correctly

any /bin/ceph call hangs,
strace shows

```
rt_sigaction(SIGRT_1, {sa_handler=0x7fd5b749cb70, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x7fd5b7454db0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fd5b491c000
mprotect(0x7fd5b491d000, 8388608, PROT_READ|PROT_WRITE) = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7fd5b511c910, parent_tid=0x7fd5b511c910, exit_signal=0, stack=0x7fd5b491c000, stack_size=0x7fff00, tls=0x7fd5b511c640} => {parent_tid=[148956]}, 88) = 148956
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x555f73973470, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
futex(0x7fd5b7b40fe8, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=133387, tv_nsec=161061723}, FUTEX_BITSET_MATCH_ANY) = 0
futex(0x7fd5b7b40ff0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fd5b0000b60, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=219787, tv_nsec=156209293}, FUTEX_BITSET_MATCH_ANY) = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7fd5b511c910, parent_tid=0x7fd5b511c910, exit_signal=0, stack=0x7fd5b491c000, stack_size=0x7fff00, tls=0x7fd5b511c640} => {parent_tid=[148957]}, 88) = 148957
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7fd5b7b40fec, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fd5b7b40ff0, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7fd5b511c910, parent_tid=0x7fd5b511c910, exit_signal=0, stack=0x7fd5b491c000, stack_size=0x7fff00, tls=0x7fd5b511c640} => {parent_tid=[148958]}, 88) = 148958
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7fd5b7b40fe8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x555f73973470, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fd5b0000b60, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=133392, tv_nsec=172148409}, FUTEX_BITSET_MATCH_ANY) = 0
```
there is no way to know communication between hosts is broken
