### ISSUE TITLE
cephadm don-t work

### ISSUE THREAD

**Issue by ilusha0561h** [ceph/ceph-ansible#7629]
```
root@ceph-node-2:/home/ubuntu# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
===
```
root@ceph-node-2:/home/ubuntu# uname -a
Linux ceph-node-2 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
===
root@ceph-node-1:/home/ubuntu# ansible-playbook --version
ansible-playbook [core 2.15.13]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

====
root@ceph-node-1:/home/ubuntu/ceph-ansible# ceph -v
ceph version 17.2.8 (f817ceb7f187defb1d021d6328fa833eb8e943b3) quincy (stable)

Good afternoon ceph adm is not working I can't connect bucket storage

root@ceph-node-1:/home/ubuntu# cephadm version
Traceback (most recent call last):
  File "/usr/sbin/cephadm", line 9930, in <module>
    main()
  File "/usr/sbin/cephadm", line 9918, in main
    r = ctx.func(ctx)
  File "/usr/sbin/cephadm", line 2221, in _infer_image
    ctx.image = infer_local_ceph_image(ctx, ctx.container_engine.path)
  File "/usr/sbin/cephadm", line 2304, in infer_local_ceph_image
    container_info = get_container_info(ctx, daemon, daemon_name is not None)
  File "/usr/sbin/cephadm", line 2267, in get_container_info
    matching_daemons = [d for d in daemons if daemon_name_or_type(d) == daemon_filter and d['fsid'] == ctx.fsid]
  File "/usr/sbin/cephadm", line 2267, in <listcomp>
    matching_daemons = [d for d in daemons if daemon_name_or_type(d) == daemon_filter and d['fsid'] == ctx.fsid]
  File "/usr/sbin/cephadm", line 229, in __getattr__
    return super().__getattribute__(name)
AttributeError: 'CephadmContext' object has no attribute 'fsid'

MODULE
balancer           on (always on)
crash              on (always on)
devicehealth       on (always on)
orchestrator       on (always on)
pg_autoscaler      on (always on)
progress           on (always on)
rbd_support        on (always on)
status             on (always on)
telemetry          on (always on)
volumes            on (always on)
cephadm            on
dashboard          on
prometheus         on
alerts             -
influx             -
insights           -
iostat             -
localpool          -
mirroring          -
nfs                -
osd_perf_query     -
osd_support        -
restful            -
selftest           -
snap_schedule      -
stats              -
telegraf           -
test_orchestrator  -
zabbix             -
Error ENOENT: No orchestrator configured (try `ceph orch set backend`)

root@ceph-node-1:/home/ubuntu/ceph-ansible# ceph orch set backend cephadm
Error EINVAL: Module 'cephadm' not found
root@ceph-node-1:/home/ubuntu/ceph-ansible# ceph mgr module enable cephadm --force
module 'cephadm' is already enabled

root@ceph-node-1:/home/ubuntu/ceph-ansible# ceph orch set backend cephadm
Error EINVAL: Module 'cephadm' not found

**Comment by ilusha0561h** [comment]
root@ceph-node-1:/home/ubuntu# radosgw-admin bucket notification create \
  --bucket=new-bucket-93b8cf6e \
  --topic=my-sns-topic \
  --events="s3:ObjectCreated:*" \
  --s3-user=my-api \
  --notification-endpoint="https://photometry-stage.imbalanced.tech/photometry/v0/s3toredisapi/api/S3Images/refresh-Ceph-links"

**Comment by ilusha0561h** [comment]
how to set up events ?

**Comment by ilusha0561h** [comment]
ERROR: invalid flag --events=s3:ObjectCreated:*
